// core_rtl/npu_top.h -- drop-in top level for system integration wrappers that runs instruction streams on the
// RTL-accurate core.
//
// A wrapper written for the native top level (../npu_top.h, class sauria::NpuTop) builds unchanged when its model
// root points at this directory: same class name, template parameters, constructor, ports, attach_perf(), set_dram()
// and decoder_inst. Inside, two engines share the host bus:
//   - the native top level (../npu_top.h) for the native configuration registers, the SRAM windows, the OBP / RCE
//     tables, i_start, and for instructions pushed without extension registers (functional decoder, as before);
//   - HasNpuTop (../has/has_npu_top.h: RTL-accurate core, HAS data flow controller, DMA, epilogue and vector unit) for
//     instructions pushed after writing extension registers 0x4000046C..0x400004E7 (programs generated by
//     tools/fe/fe_emit_insts.py, tools/fe/fe_vit_full.py).
// Host bus routing:
//   0x40000400..0x40000468  instruction parameters: written to both engines
//   0x4000046C..0x400004E7  extension registers: HasNpuTop only; marks the next push for HasNpuTop
//   0x40000310              push, lane A: HasNpuTop when extension registers were written since the previous push,
//                           otherwise the native decoder
//   0x40000318, 0x4000031C  STATUS, RETIRED of HasNpuTop (read and write)
//   everything else         native top level
// decoder_inst reports the instructions of both engines (queue size and busy state), so a wrapper that detects
// completion from the queue size keeps working. o_done / o_deadlock are those of the native top level.
// Performance counters (attach_perf): the native top level counts as before (total_cycles every clock, the other
// fields for instructions of the native decoder). Each HasNpuTop instruction adds, when it retires:
//   exec_cycles, processing_cycles += instruction cycles (RTL-accurate core, modelled DMA and vector unit)
//   dma_engine_cycles += cycles waiting for the DMA      obp_cycles += epilogue cycles
//   reduction_engine_cycles += FUSED_ATTN / LAYERNORM cycles    pooling_engine_cycles += ELEM_WISE cycles
//   ddr_read_bytes, ddr_write_bytes += DMA bytes
//
// DRAM: set_dram() gives the same byte vector to both engines. HasNpuTop addresses are offsets in that vector. Address
// values of the extension registers at or above dram_base() (default 0x80000000, the start of system RAM in a wrapper
// that stores RAM-relative offsets) are converted to offsets, like the wrapper does for the parameter registers.
// HasNpuTop's private staging area is placed at staging_base() (default 0x10000000), above every RAM offset.
//
// Environment (read at construction):
//   SAURIA_CORE_RTL_PROFILE  recommended (default) | proposals | legacy   -- HasNpuTop run profile
//   SAURIA_CORE_RTL_C_BCAST  1: bias preload by broadcast descriptor (timing only; reproduces the ViT-B/16 reference cycles)
//   SAURIA_CORE_RTL_TRACE    1: one line per executed HasNpuTop instruction on stdout
//   HAS_*                    knobs of has::Knobs::from_env() (for example HAS_SP_PRESET=gvu68k), as for tools/has/tb_has_npu_top
#ifndef SAURIA_CORE_RTL_NPU_TOP_H
#define SAURIA_CORE_RTL_NPU_TOP_H

#ifndef SAURIA_CORE_BACKEND_RTL_REF
#define SAURIA_CORE_BACKEND_RTL_REF
#endif
#ifndef FX1_A3_SRAM_BACKDOOR_LOAD
#define FX1_A3_SRAM_BACKDOOR_LOAD
#endif

#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include "../has/has_npu_top.h"

// The native top level is used under another name; this header defines sauria::NpuTop.
#define NpuTop NativeNpuTop
#include "../npu_top.h"
#undef NpuTop

namespace sauria
{
    template <
        int X_DIM = 32,
        int Y_DIM = 32,
        typename T_ACT = int8_t,
        typename T_WEI = int8_t,
        typename T_PSUM = int32_t,
        int FIFO_DEPTH = 16,
        int PE_LAT = X_DIM + Y_DIM,
        int EXTRA_CSREG = 1,
        int SRAMA_CAP = 5056,
        int SRAMB_CAP = 5184,
        int SRAMC_CAP = 1536>
    class NpuTop : public sc_module
    {
    public:
        typedef NativeNpuTop<X_DIM, Y_DIM, T_ACT, T_WEI, T_PSUM, FIFO_DEPTH, PE_LAT, EXTRA_CSREG, SRAMA_CAP, SRAMB_CAP,
                             SRAMC_CAP>
            Native;

        sc_in<bool> i_clk{"i_clk"};
        sc_in<bool> i_rstn{"i_rstn"};
        sc_in<bool> i_soft_reset{"i_soft_reset"};
        sc_in<bool> i_start{"i_start"};
        sc_out<bool> o_done{"o_done"};
        sc_out<bool> o_deadlock{"o_deadlock"};
        sc_in<uint32_t> i_mvm_k{"i_mvm_k"};
        sc_in<uint32_t> i_host_addr{"i_host_addr"};
        sc_in<bool> i_host_wren{"i_host_wren"};
        sc_in<bool> i_host_rden{"i_host_rden"};
        sc_in<host_data_t> i_host_wdata{"i_host_wdata"};
        sc_in<host_mask_t> i_host_wmask{"i_host_wmask"};
        sc_out<host_data_t> o_host_rdata{"o_host_rdata"};
        sc_in<float> i_threshold{"i_threshold"};
        sc_in<sc_bv<3>> i_select{"i_select"};
        sc_in<uint32_t> i_total_contexts{"i_total_contexts"};

        // Queue view over both engines, with the accessors of the native decoder that wrappers use.
        struct DecoderView
        {
            NpuTop *top{nullptr};
            size_t get_queue_a_size() const { return top->native_queue_a() + top->has_pending(); }
            size_t get_queue_b_size() const { return top->native_queue_b(); }
            int get_state_a() const { return top->native_state_a() | (top->has_pending() ? 1 : 0); }
            int get_state_b() const { return top->native_state_b(); }
        };
        DecoderView *decoder_inst{nullptr};

        Native *native{nullptr};
        has::HasNpuTop *rtl{nullptr};

        SC_HAS_PROCESS(NpuTop);
        NpuTop(sc_module_name nm, const PeConfig &pe_cfg = PeConfig()) : sc_module(nm)
        {
            native = new Native("native", pe_cfg);
            native->i_clk(i_clk);
            native->i_rstn(i_rstn);
            native->i_soft_reset(i_soft_reset);
            native->i_start(i_start);
            native->o_done(o_done);
            native->o_deadlock(o_deadlock);
            native->i_mvm_k(i_mvm_k);
            native->i_host_addr(n_addr_);
            native->i_host_wren(n_wren_);
            native->i_host_rden(n_rden_);
            native->i_host_wdata(i_host_wdata);
            native->i_host_wmask(i_host_wmask);
            native->o_host_rdata(n_rdata_);
            native->i_threshold(i_threshold);
            native->i_select(i_select);
            native->i_total_contexts(i_total_contexts);

            const has::Profile prof = env_profile();
            rtl = new has::HasNpuTop("rtl", has::profile_knobs(prof, has::Knobs::from_env()));   // HAS_* knobs, e.g. HAS_SP_PRESET
            rtl->apply_profile(prof);
            rtl->c_bias_bcast = rtl->c_bias_bcast || env_flag("SAURIA_CORE_RTL_C_BCAST");
            rtl->trace = env_flag("SAURIA_CORE_RTL_TRACE");
            rtl->i_clk(i_clk);
            rtl->i_rstn(i_rstn);
            rtl->i_host_addr(h_addr_);
            rtl->i_host_wren(h_wren_);
            rtl->i_host_rden(h_rden_);
            rtl->i_host_wdata(h_wdata_);
            rtl->i_host_wmask(i_host_wmask);
            rtl->o_host_rdata(h_rdata_);
            rtl->o_irq(h_irq_);
            rtl->o_done(h_done_);
            rtl->o_deadlock(h_deadlock_);

            view_.top = this;
            decoder_inst = &view_;

            SC_METHOD(route);
            sensitive << i_host_addr << i_host_wren << i_host_rden << i_host_wdata << ext_seen_;
            SC_METHOD(read_mux);
            sensitive << i_host_addr << n_rdata_ << h_rdata_;
            SC_METHOD(on_clock);
            sensitive << i_clk.pos();
            dont_initialize();
        }
        ~NpuTop()
        {
            delete native;
            delete rtl;
        }

        void attach_perf(fx1::PerfCounters *p)
        {
            native->attach_perf(p);
            perf_ = p;
        }
        void set_dram(std::vector<uint8_t> *dram)
        {
            native->set_dram(dram);
            rtl->set_dram(dram);
            rtl->set_staging_base(staging_base_);
        }
        // Must be called before set_dram().
        void set_staging_base(uint32_t b) { staging_base_ = b; }
        uint32_t staging_base() const { return staging_base_; }
        void set_dram_base(uint32_t b) { dram_base_ = b; }
        uint32_t dram_base() const { return dram_base_; }

        size_t has_pending() const { return rtl->mmio.queued() + (rtl->mmio.executing() ? 1 : 0); }
        size_t native_queue_a() const { return native->decoder_inst ? native->decoder_inst->get_queue_a_size() : 0; }
        size_t native_queue_b() const { return native->decoder_inst ? native->decoder_inst->get_queue_b_size() : 0; }
        int native_state_a() const { return native->decoder_inst ? native->decoder_inst->get_state_a() : 0; }
        int native_state_b() const { return native->decoder_inst ? native->decoder_inst->get_state_b() : 0; }

    private:
        static constexpr uint32_t PARAM_LO = 0x40000400, PARAM_HI = 0x40000468;   // inclusive
        static constexpr uint32_t EXT_LO = 0x4000046C, EXT_END = 0x400004E8;      // exclusive end
        static constexpr uint32_t PUSH_A = 0x40000310, STATUS = 0x40000318, RETIRED = 0x4000031C;
        // Extension registers that hold DRAM addresses (scale, shift, LUT, parameter block, mask).
        static bool ext_is_address(uint32_t a)
        {
            return a == 0x40000490 || a == 0x40000494 || a == 0x40000498 || a == 0x400004E0 || a == 0x400004E4;
        }
        static bool is_ext(uint32_t a) { return a >= EXT_LO && a < EXT_END; }
        static bool is_param(uint32_t a) { return a >= PARAM_LO && a <= PARAM_HI; }
        static bool is_rtl_status(uint32_t a) { return a == STATUS || a == RETIRED; }

        void route()
        {
            const uint32_t a = i_host_addr.read();
            const bool w = i_host_wren.read(), r = i_host_rden.read();
            const bool to_rtl_push = a == PUSH_A && ext_seen_.read();
            const bool rtl_only = is_ext(a) || is_rtl_status(a) || to_rtl_push;
            n_addr_.write(a);
            n_wren_.write(w && !rtl_only);
            n_rden_.write(r && !rtl_only);
            h_addr_.write(a);
            h_wren_.write(w && (rtl_only || is_param(a)));
            h_rden_.write(r && is_rtl_status(a));
            host_data_t d = i_host_wdata.read();
            if (w && ext_is_address(a))
            {
                const uint32_t v = static_cast<uint32_t>(d[0]);
                if (v >= dram_base_) d[0] = static_cast<double>(v - dram_base_);
            }
            h_wdata_.write(d);
        }
        void read_mux()
        {
            o_host_rdata.write(is_rtl_status(i_host_addr.read()) ? h_rdata_.read() : n_rdata_.read());
        }
        void on_clock()
        {
            // Clock period for HasNpuTop's cycle accounting: the shortest distance between two rising edges (a gated
            // clock only adds longer gaps).
            const sc_time now = sc_time_stamp();
            if (have_edge_)
            {
                const sc_time d = now - last_edge_;
                if (d > SC_ZERO_TIME && (period_ == SC_ZERO_TIME || d < period_))
                {
                    period_ = d;
                    rtl->set_clock_period(period_);
                }
            }
            last_edge_ = now;
            have_edge_ = true;
            add_rtl_counters();
            if (!i_rstn.read()) { ext_seen_.write(false); return; }
            if (i_host_wren.read())
            {
                const uint32_t a = i_host_addr.read();
                if (is_ext(a)) ext_seen_.write(true);
                else if (a == PUSH_A) ext_seen_.write(false);
            }
        }
        struct RtlSnap { uint64_t instr{0}, cycles{0}, dma{0}, obp{0}, rce{0}, elem{0}, rd{0}, wr{0}; };
        RtlSnap rtl_snap() const
        {
            RtlSnap s;
            s.instr = rtl->st.instr; s.cycles = rtl->st.cycles; s.dma = rtl->st.dma_cycles; s.obp = rtl->st.obp_cycles;
            s.rce = rtl->st.rce_cycles; s.elem = rtl->st.elem_cycles;
            s.rd = rtl->dma_stats().read_bytes; s.wr = rtl->dma_stats().write_bytes;
            return s;
        }
        void add_rtl_counters()
        {
            const RtlSnap s = rtl_snap();
            if (s.instr == snap_.instr) return;
            if (perf_)
            {
                perf_->exec_cycles += s.cycles - snap_.cycles;
                perf_->processing_cycles += s.cycles - snap_.cycles;
                perf_->dma_engine_cycles += s.dma - snap_.dma;
                perf_->obp_cycles += s.obp - snap_.obp;
                perf_->reduction_engine_cycles += s.rce - snap_.rce;
                perf_->pooling_engine_cycles += s.elem - snap_.elem;
                perf_->ddr_read_bytes += s.rd - snap_.rd;
                perf_->ddr_write_bytes += s.wr - snap_.wr;
            }
            snap_ = s;
        }
        static bool env_flag(const char *n)
        {
            const char *v = std::getenv(n);
            return v && v[0] == '1';
        }
        static has::Profile env_profile()
        {
            const char *v = std::getenv("SAURIA_CORE_RTL_PROFILE");
            if (v && std::strcmp(v, "legacy") == 0) return has::Profile::Legacy;
            if (v && std::strcmp(v, "proposals") == 0) return has::Profile::Proposals;
            return has::Profile::Recommended;
        }

        DecoderView view_;
        fx1::PerfCounters *perf_{nullptr};
        RtlSnap snap_;
        uint32_t staging_base_{0x10000000u};
        uint32_t dram_base_{0x80000000u};
        sc_time last_edge_{SC_ZERO_TIME}, period_{SC_ZERO_TIME};
        bool have_edge_{false};
        sc_signal<bool> ext_seen_{"ext_seen", false};
        sc_signal<uint32_t> n_addr_{"n_addr"}, h_addr_{"h_addr"};
        sc_signal<bool> n_wren_{"n_wren"}, n_rden_{"n_rden"}, h_wren_{"h_wren"}, h_rden_{"h_rden"};
        sc_signal<host_data_t> h_wdata_{"h_wdata"}, n_rdata_{"n_rdata"}, h_rdata_{"h_rdata"};
        sc_signal<bool> h_irq_{"h_irq"}, h_done_{"h_done"}, h_deadlock_{"h_deadlock"};
    };
} // namespace sauria

#endif
