#!/usr/bin/env python3
"""Generate the 4K (3840x2160, HAS maximum) vectors from the Python reference (DEC-37).

The input is a deterministic pattern, implemented identically here
(pattern()) and in tools/run_raw.cpp (synthetic_sample()), so neither the
16 MB input nor the 12 MB output is committed. Each case directory
tests/data/4k/<case>/ holds:
  profile.csrw         CSR writes (make_profile preset, grey world on the pattern)
  meta.txt             "width height frames"
  expected_stats.txt   statistics readout script with the expected values
  expected_nv12.sha256 "<sha256> <out_w> <out_h>" of the last frame's NV12
CTest runs fx1_isp_run_raw --synthetic with --check-stats and --expect-sha256.
--check verifies the committed files are up to date.
"""

import argparse
import hashlib
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "reference"))
sys.path.insert(0, HERE)
from fx1_isp_ref import blocks, regs as regs_mod  # noqa: E402
from fx1_isp_ref.stats import readout_script  # noqa: E402
import make_profile  # noqa: E402

OUT = os.path.join(HERE, "..", "tests", "data", "4k")
W, H = 3840, 2160
M32 = 0xFFFFFFFF


def pattern(w, h):
    """12-bit samples: hashed noise on a gradient whose sense flips on a 256-pixel checkerboard."""
    x = np.arange(w, dtype=np.uint64)[None, :]
    y = np.arange(h, dtype=np.uint64)[:, None]
    k = ((x * 0x9E3779B1) & M32) ^ ((y * 0x85EBCA77) & M32)
    k ^= k >> 15
    k = (k * 0x2C1B3C6D) & M32
    k ^= k >> 12
    xi, yi = x.astype(np.int64), y.astype(np.int64)
    base = xi * 3000 // w + yi * 1000 // h
    flip = ((xi // 256 + yi // 256) & 1) == 1
    base = np.where(flip, 4000 - base, base)
    return np.clip(base + (k & 0xFF).astype(np.int64) - 128, 0, 4095).astype(np.uint16)


CASES = [
    # name, Bayer, preset, extra writes: all blocks at 4K with the Resizer off (NV12 3840x2160)
    ("full_rggb_3840x2160", "RGGB", "full", [("RESIZER_CTRL", 0)]),
    # GBRG crops to 3840x2158; FHD then needs DEC-23 (k lowered so both axes stay >= the output)
    ("full_gbrg_3840x2160_fhd", "GBRG", "full", []),
]


def build(name, bayer, preset, extra, check):
    raw = pattern(W, H)
    writes, note = make_profile.profile_writes(raw.astype(np.int64), W, H, bayer, preset)
    writes = writes + list(extra)
    frames = make_profile.FRAMES[preset]
    r = regs_mod.Registers()
    r.write("COMMON_FRAME_WIDTH", W)
    r.write("COMMON_FRAME_HEIGHT", H)
    for n, v in writes:
        r.write(n, v)
    for _ in range(frames):
        y, uv = blocks.run_frame(raw, r, {})
    files = {
        "profile.csrw": ("# generated by tools/gen_4k_vectors.py, preset %s (%s)\n" % (preset, note) +
                         "".join("%s 0x%X\n" % (n, v) for n, v in writes)).encode(),
        "meta.txt": ("%d %d %d\n" % (W, H, frames)).encode(),
        "expected_stats.txt": "".join(readout_script(r)).encode(),
        "expected_nv12.sha256": ("%s %d %d\n" % (hashlib.sha256(y.tobytes() + uv.tobytes()).hexdigest(),
                                                 y.shape[1], y.shape[0])).encode(),
    }
    d = os.path.join(OUT, name)
    os.makedirs(d, exist_ok=True)
    stale = []
    for fn, data in files.items():
        p = os.path.join(d, fn)
        if check:
            if not os.path.exists(p) or open(p, "rb").read() != data:
                stale.append(p)
        else:
            open(p, "wb").write(data)
    return stale


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    stale = []
    for c in CASES:
        stale += build(*c, a.check)
    if stale:
        sys.exit("gen_4k_vectors.py: out of date:\n  " + "\n  ".join(stale))
    print("%s %d 4K cases" % ("checked" if a.check else "wrote", len(CASES)))


if __name__ == "__main__":
    main()
