/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * SAURIA NPU v4 register ABI. Offsets are relative to CDC_NPU0_BASE.
 * All accesses are aligned 32-bit little-endian words.
 */
#ifndef CDC_SOC_REGS_NPU_V4_H
#define CDC_SOC_REGS_NPU_V4_H

#define CDC_NPU_CTRL                0x0000u
#define CDC_NPU_STATUS              0x0004u
#define CDC_NPU_IRQ_ENABLE          0x0008u
#define CDC_NPU_IRQ_STATUS          0x000Cu
#define CDC_NPU_SRC_ADDR            0x0010u
#define CDC_NPU_DST_ADDR            0x0014u
#define CDC_NPU_SCRATCH_ADDR        0x0018u
#define CDC_NPU_SRC_SIZE_BYTES      0x001Cu
#define CDC_NPU_DST_SIZE_BYTES      0x0020u
#define CDC_NPU_WIDTH               0x0024u
#define CDC_NPU_HEIGHT              0x0028u
#define CDC_NPU_SRC_STRIDE_BYTES    0x002Cu
#define CDC_NPU_FORMAT              0x0030u
#define CDC_NPU_OP_MODE             0x0034u
#define CDC_NPU_WEIGHTS_ADDR        0x0038u
#define CDC_NPU_PARAM_ADDR          0x003Cu
#define CDC_NPU_WEIGHTS_SIZE_BYTES  0x0040u

#define CDC_NPU_K_DIMENSION         0x1000u
#define CDC_NPU_ZERO_THRESHOLD_FP32 0x1004u
#define CDC_NPU_ROWS_ACTIVE         0x1008u
#define CDC_NPU_DILATION_PATTERN    0x100Cu
#define CDC_NPU_CYCLE_COUNT         0x1010u
#define CDC_NPU_BYTES_READ          0x1014u
#define CDC_NPU_BYTES_WRITTEN       0x1018u
#define CDC_NPU_LAST_ERROR          0x101Cu
#define CDC_NPU_CORE_ID             0x1020u

/* SAURIA MP1 V1.1 v4.1 software parameters. */
#define CDC_NPU_INPUT_OFFSET        0x1100u
#define CDC_NPU_WEIGHT_OFFSET       0x1104u
#define CDC_NPU_OUTPUT_OFFSET       0x1108u
#define CDC_NPU_ACTIVATION_MIN      0x110Cu
#define CDC_NPU_ACTIVATION_MAX      0x1110u
#define CDC_NPU_BIAS_ADDR           0x1114u
#define CDC_NPU_BIAS_SIZE_BYTES     0x1118u
#define CDC_NPU_MULTIPLIER_ADDR     0x111Cu
#define CDC_NPU_MULTIPLIER_SIZE_BYTES 0x1120u
#define CDC_NPU_SHIFT_ADDR          0x1124u
#define CDC_NPU_SHIFT_SIZE_BYTES    0x1128u

/* Low 32-bit performance/evaluation counters. */
#define CDC_NPU_PERF_EXEC_CYCLES    0x1200u
#define CDC_NPU_PERF_STALL_CYCLES   0x1204u
#define CDC_NPU_PERF_MAC_OPS        0x1208u
#define CDC_NPU_PERF_ACTIVE_PE_CYCLES 0x120Cu
#define CDC_NPU_PERF_TOTAL_PE_CYCLES  0x1210u
#define CDC_NPU_EVAL_TOTAL_CYCLES   0x1214u
#define CDC_NPU_EVAL_PROCESSING_CYCLES 0x1218u
#define CDC_NPU_EVAL_TRANSFER_CYCLES 0x121Cu
#define CDC_NPU_EVAL_DMA_STALL_CYCLES 0x1220u
#define CDC_NPU_EVAL_DDR_READ_BYTES 0x1224u
#define CDC_NPU_EVAL_DDR_WRITE_BYTES 0x1228u

/*
 * Raw/native SAURIA MP1 V1.1 offsets from sauria_types.h. These are relative
 * to CDC_NPU0_BASE and are used by the native v4.1 bridge path.
 */
#define CDC_NPU_NATIVE_SAURIA_MEM_ADDR_MASK 0x003C0000u
#define CDC_NPU_NATIVE_CFG_REGS_OFFSET      0x00000000u
#define CDC_NPU_NATIVE_SRAMA_OFFSET         0x00040000u
#define CDC_NPU_NATIVE_SRAMB_OFFSET         0x00080000u
#define CDC_NPU_NATIVE_SRAMC_OFFSET         0x000C0000u

#define CDC_NPU_NATIVE_CFG_CON_OFFSET       0x00000200u
#define CDC_NPU_NATIVE_CFG_ACT_OFFSET       0x00000400u
#define CDC_NPU_NATIVE_CFG_WEI_OFFSET       0x00000600u
#define CDC_NPU_NATIVE_CFG_OUT_OFFSET       0x00000800u
#define CDC_NPU_NATIVE_CFG_LAYER_OFFSET     0x00000A00u

#define CDC_NPU_NATIVE_CFG_ACT_BASE_ADDR    (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x80u)
#define CDC_NPU_NATIVE_CFG_WEI_BASE_ADDR    (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x80u)
#define CDC_NPU_NATIVE_CFG_OUT_BASE_ADDR    (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x80u)

#define CDC_NPU_NATIVE_WEI_WLIM             (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x10u)
#define CDC_NPU_NATIVE_WEI_WSTEP            (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x14u)
#define CDC_NPU_NATIVE_WEI_KLIM             (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x18u)
#define CDC_NPU_NATIVE_WEI_KSTEP            (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x1Cu)
#define CDC_NPU_NATIVE_WEI_TIL_XLIM         (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x20u)
#define CDC_NPU_NATIVE_WEI_TIL_XSTEP        (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x24u)
#define CDC_NPU_NATIVE_WEI_COLS_ACTIVE      (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x28u)
#define CDC_NPU_NATIVE_WEI_WALIGNED         (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x2Cu)

#define CDC_NPU_NATIVE_ACT_XLIM             (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x14u)
#define CDC_NPU_NATIVE_ACT_XSTEP            (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x18u)
#define CDC_NPU_NATIVE_ACT_YLIM             (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x1Cu)
#define CDC_NPU_NATIVE_ACT_YSTEP            (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x20u)
#define CDC_NPU_NATIVE_ACT_CHLIM            (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x24u)
#define CDC_NPU_NATIVE_ACT_CHSTEP           (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x2Cu)
#define CDC_NPU_NATIVE_ACT_TIL_XLIM         (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x30u)
#define CDC_NPU_NATIVE_ACT_TIL_XSTEP        (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x34u)
#define CDC_NPU_NATIVE_ACT_TIL_YLIM         (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x38u)
#define CDC_NPU_NATIVE_ACT_TIL_YSTEP        (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x3Cu)

#define CDC_NPU_NATIVE_NCONTEXTS            (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x00u)
#define CDC_NPU_NATIVE_TIL_CYLIM            (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x14u)
#define CDC_NPU_NATIVE_TIL_CYSTEP           (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x18u)
#define CDC_NPU_NATIVE_TIL_CKLIM            (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x1Cu)
#define CDC_NPU_NATIVE_TIL_CKSTEP           (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x20u)
#define CDC_NPU_NATIVE_INACTIVE_COLS        (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x24u)
#define CDC_NPU_NATIVE_PRELOAD_EN           (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x28u)

#define CDC_NPU_NATIVE_IN_H                 (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x00u)
#define CDC_NPU_NATIVE_IN_W                 (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x04u)
#define CDC_NPU_NATIVE_IN_C                 (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x08u)
#define CDC_NPU_NATIVE_OUT_H                (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x0Cu)
#define CDC_NPU_NATIVE_OUT_W                (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x10u)
#define CDC_NPU_NATIVE_OUT_C                (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x14u)
#define CDC_NPU_NATIVE_KERNEL_H             (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x18u)
#define CDC_NPU_NATIVE_KERNEL_W             (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x1Cu)
#define CDC_NPU_NATIVE_STRIDE               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x20u)
#define CDC_NPU_NATIVE_PADDING              (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x24u)
#define CDC_NPU_NATIVE_DILATION             (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x28u)
#define CDC_NPU_NATIVE_DIL_PAT              (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x2Cu)
#define CDC_NPU_NATIVE_TILE_X               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x30u)
#define CDC_NPU_NATIVE_TILE_Y               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x34u)
#define CDC_NPU_NATIVE_TILE_K               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x38u)
#define CDC_NPU_NATIVE_TILE_C               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x3Cu)
#define CDC_NPU_NATIVE_X_USED               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x40u)
#define CDC_NPU_NATIVE_Y_USED               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x44u)

#define CDC_NPU_CTRL_ENABLE         (1u << 0)
#define CDC_NPU_CTRL_START          (1u << 1)
#define CDC_NPU_CTRL_SOFT_RESET     (1u << 2)
#define CDC_NPU_CTRL_IRQ_EN         (1u << 3)

#define CDC_NPU_STATUS_BUSY         (1u << 0)
#define CDC_NPU_STATUS_DONE         (1u << 1)
#define CDC_NPU_STATUS_ERROR        (1u << 2)
#define CDC_NPU_STATUS_IDLE         (1u << 3)

#define CDC_NPU_IRQ_DONE            (1u << 0)
#define CDC_NPU_IRQ_ERROR           (1u << 1)

#define CDC_NPU_FORMAT_INT8_INT8_INT32 1u
#define CDC_NPU_FORMAT_INT8_INT8_INT8  2u
#define CDC_NPU_OP_GEMM                0u
#define CDC_NPU_CORE_ID_VALUE          0x53413431u

#define CDC_NPU_ERROR_NONE               0u
#define CDC_NPU_ERROR_DISABLED           1u
#define CDC_NPU_ERROR_BUSY               2u
#define CDC_NPU_ERROR_INVALID_DIMENSIONS 3u
#define CDC_NPU_ERROR_INVALID_FORMAT     4u
#define CDC_NPU_ERROR_INVALID_OPERATION  5u
#define CDC_NPU_ERROR_INVALID_ADDRESS    6u
#define CDC_NPU_ERROR_INVALID_SIZE       7u
#define CDC_NPU_ERROR_DMA_READ           8u
#define CDC_NPU_ERROR_DMA_WRITE          9u
#define CDC_NPU_ERROR_CORE_DEADLOCK      10u
#define CDC_NPU_ERROR_CORE_TIMEOUT       11u
#define CDC_NPU_ERROR_RESET_ABORTED      12u

#endif /* CDC_SOC_REGS_NPU_V4_H */
