/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * SAURIA NPU V4.4 register ABI. Offsets are relative to CDC_NPU0_BASE.
 * All accesses are aligned 32-bit little-endian words.
 */
#ifndef CDC_SOC_REGS_NPU_V4_H
#define CDC_SOC_REGS_NPU_V4_H

#define CDC_NPU_WRAPPER_BASE        0x00030000u
#define CDC_NPU_CTRL                (CDC_NPU_WRAPPER_BASE + 0x0000u)
#define CDC_NPU_STATUS              (CDC_NPU_WRAPPER_BASE + 0x0004u)
#define CDC_NPU_IRQ_ENABLE          (CDC_NPU_WRAPPER_BASE + 0x0008u)
#define CDC_NPU_IRQ_STATUS          (CDC_NPU_WRAPPER_BASE + 0x000Cu)
#define CDC_NPU_SRC_ADDR            (CDC_NPU_WRAPPER_BASE + 0x0010u)
#define CDC_NPU_DST_ADDR            (CDC_NPU_WRAPPER_BASE + 0x0014u)
#define CDC_NPU_SCRATCH_ADDR        (CDC_NPU_WRAPPER_BASE + 0x0018u)
#define CDC_NPU_SRC_SIZE_BYTES      (CDC_NPU_WRAPPER_BASE + 0x001Cu)
#define CDC_NPU_DST_SIZE_BYTES      (CDC_NPU_WRAPPER_BASE + 0x0020u)
#define CDC_NPU_WIDTH               (CDC_NPU_WRAPPER_BASE + 0x0024u)
#define CDC_NPU_HEIGHT              (CDC_NPU_WRAPPER_BASE + 0x0028u)
#define CDC_NPU_SRC_STRIDE_BYTES    (CDC_NPU_WRAPPER_BASE + 0x002Cu)
#define CDC_NPU_FORMAT              (CDC_NPU_WRAPPER_BASE + 0x0030u)
#define CDC_NPU_OP_MODE             (CDC_NPU_WRAPPER_BASE + 0x0034u)
#define CDC_NPU_WEIGHTS_ADDR        (CDC_NPU_WRAPPER_BASE + 0x0038u)
#define CDC_NPU_PARAM_ADDR          (CDC_NPU_WRAPPER_BASE + 0x003Cu)
#define CDC_NPU_WEIGHTS_SIZE_BYTES  (CDC_NPU_WRAPPER_BASE + 0x0040u)

#define CDC_NPU_K_DIMENSION         (CDC_NPU_WRAPPER_BASE + 0x1000u)
#define CDC_NPU_ZERO_THRESHOLD_FP32 (CDC_NPU_WRAPPER_BASE + 0x1004u)
#define CDC_NPU_ROWS_ACTIVE         (CDC_NPU_WRAPPER_BASE + 0x1008u)
#define CDC_NPU_DILATION_PATTERN    (CDC_NPU_WRAPPER_BASE + 0x100Cu)
#define CDC_NPU_CYCLE_COUNT         (CDC_NPU_WRAPPER_BASE + 0x1010u)
#define CDC_NPU_BYTES_READ          (CDC_NPU_WRAPPER_BASE + 0x1014u)
#define CDC_NPU_BYTES_WRITTEN       (CDC_NPU_WRAPPER_BASE + 0x1018u)
#define CDC_NPU_LAST_ERROR          (CDC_NPU_WRAPPER_BASE + 0x101Cu)
#define CDC_NPU_CORE_ID             (CDC_NPU_WRAPPER_BASE + 0x1020u)

/* Optional parameters used by the CDC software-facing 64x64 GEMM path. */
#define CDC_NPU_INPUT_OFFSET        (CDC_NPU_WRAPPER_BASE + 0x1100u)
#define CDC_NPU_WEIGHT_OFFSET       (CDC_NPU_WRAPPER_BASE + 0x1104u)
#define CDC_NPU_OUTPUT_OFFSET       (CDC_NPU_WRAPPER_BASE + 0x1108u)
#define CDC_NPU_ACTIVATION_MIN      (CDC_NPU_WRAPPER_BASE + 0x110Cu)
#define CDC_NPU_ACTIVATION_MAX      (CDC_NPU_WRAPPER_BASE + 0x1110u)
#define CDC_NPU_BIAS_ADDR           (CDC_NPU_WRAPPER_BASE + 0x1114u)
#define CDC_NPU_BIAS_SIZE_BYTES     (CDC_NPU_WRAPPER_BASE + 0x1118u)
#define CDC_NPU_MULTIPLIER_ADDR     (CDC_NPU_WRAPPER_BASE + 0x111Cu)
#define CDC_NPU_MULTIPLIER_SIZE_BYTES (CDC_NPU_WRAPPER_BASE + 0x1120u)
#define CDC_NPU_SHIFT_ADDR          (CDC_NPU_WRAPPER_BASE + 0x1124u)
#define CDC_NPU_SHIFT_SIZE_BYTES    (CDC_NPU_WRAPPER_BASE + 0x1128u)

/* Low 32-bit performance/evaluation counters. */
#define CDC_NPU_PERF_EXEC_CYCLES    0x1200u
#define CDC_NPU_PERF_STALL_CYCLES   0x1204u
#define CDC_NPU_PERF_MAC_OPS        0x1208u
#define CDC_NPU_PERF_ACTIVE_PE_CYCLES 0x120Cu
#define CDC_NPU_PERF_TOTAL_PE_CYCLES  0x1210u
#define CDC_NPU_PERF_TOTAL_CYCLES   0x1214u
#define CDC_NPU_PERF_M              0x1218u
#define CDC_NPU_PERF_K              0x121Cu
#define CDC_NPU_PERF_N              0x1220u
#define CDC_NPU_PERF_SA_CYCLES      0x1224u
#define CDC_NPU_PERF_OBP_CYCLES     0x1228u
#define CDC_NPU_PERF_PROCESSING_CYCLES 0x1280u
#define CDC_NPU_PERF_TRANSFER_CYCLES 0x1284u
#define CDC_NPU_PERF_MAC_ENGINE_CYCLES 0x1288u
#define CDC_NPU_PERF_DMA_ENGINE_CYCLES 0x128Cu
#define CDC_NPU_PERF_ACTIVATION_ENGINE_CYCLES 0x1290u
#define CDC_NPU_PERF_POOLING_ENGINE_CYCLES 0x1294u
#define CDC_NPU_PERF_REDUCTION_ENGINE_CYCLES 0x1298u
#define CDC_NPU_PERF_DDR_READ_BYTES 0x129Cu
#define CDC_NPU_PERF_DDR_WRITE_BYTES 0x12A0u
#define CDC_NPU_PERF_DMA_READ_CYCLES 0x12A4u
#define CDC_NPU_PERF_DMA_WRITE_CYCLES 0x12A8u

/*
 * Raw/native SAURIA MP1 V1.1 V4.4 offsets. Write CFG_PROFILE before any
 * profile-dependent configuration register.
 */
#define CDC_NPU_PROFILE_V1_SAURIA              0u
#define CDC_NPU_PROFILE_V4_LINEAR              1u
#define CDC_NPU_NATIVE_SAURIA_MEM_ADDR_MASK 0x003C0000u
#define CDC_NPU_NATIVE_CFG_REGS_OFFSET      0x00000000u
#define CDC_NPU_NATIVE_SRAMA_OFFSET         0x00040000u
#define CDC_NPU_NATIVE_SRAMB_OFFSET         0x00080000u
#define CDC_NPU_NATIVE_SRAMC_OFFSET         0x000C0000u

#define CDC_NPU_NATIVE_CFG_CON_OFFSET       0x00000200u
#define CDC_NPU_NATIVE_CFG_ACT_OFFSET       0x00000400u
#define CDC_NPU_NATIVE_CFG_WEI_OFFSET       0x00000600u
#define CDC_NPU_NATIVE_CFG_OUT_OFFSET       0x00000800u
#define CDC_NPU_NATIVE_CFG_LAYER_OFFSET     0x00000A00u
#define CDC_NPU_NATIVE_CONTROL              0x00000000u
#define CDC_NPU_NATIVE_CFG_PROFILE          0x00000004u

#define CDC_NPU_NATIVE_CFG_ACT_BASE_ADDR    (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x80u)
#define CDC_NPU_NATIVE_CFG_WEI_BASE_ADDR    (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x80u)
#define CDC_NPU_NATIVE_CFG_OUT_BASE_ADDR    (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x80u)

#define CDC_NPU_NATIVE_CON_INCNTLIM         (CDC_NPU_NATIVE_CFG_CON_OFFSET + 0x00u)
#define CDC_NPU_NATIVE_CON_ACT_REPS         (CDC_NPU_NATIVE_CFG_CON_OFFSET + 0x04u)
#define CDC_NPU_NATIVE_CON_WEI_REPS         (CDC_NPU_NATIVE_CFG_CON_OFFSET + 0x08u)
#define CDC_NPU_NATIVE_V4_CON_NCONTEXTS     (CDC_NPU_NATIVE_CFG_CON_OFFSET + 0x0Cu)
#define CDC_NPU_NATIVE_V4_CON_PRELOAD_EN    (CDC_NPU_NATIVE_CFG_CON_OFFSET + 0x10u)
#define CDC_NPU_NATIVE_CON_NSPLIT           (CDC_NPU_NATIVE_CFG_CON_OFFSET + 0x14u)

#define CDC_NPU_NATIVE_ACT_ROWS_ACTIVE      (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x00u)
#define CDC_NPU_NATIVE_ACT_INCNTLIM         (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x04u)
#define CDC_NPU_NATIVE_ACT_INCNTSTEP        (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x08u)
#define CDC_NPU_NATIVE_ACT_OUTCNTLIM        (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x0Cu)
#define CDC_NPU_NATIVE_ACT_OUTCNTSTEP       (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x10u)
#define CDC_NPU_NATIVE_ACT_DIL_PAT          (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x28u)

#define CDC_NPU_NATIVE_WEI_WLIM             (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x10u)
#define CDC_NPU_NATIVE_WEI_WSTEP            (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x14u)
#define CDC_NPU_NATIVE_WEI_KLIM             (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x18u)
#define CDC_NPU_NATIVE_WEI_KSTEP            (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x1Cu)
#define CDC_NPU_NATIVE_WEI_TIL_XLIM         (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x20u)
#define CDC_NPU_NATIVE_WEI_TIL_XSTEP        (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x24u)
#define CDC_NPU_NATIVE_WEI_COLS_ACTIVE      (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x28u)
#define CDC_NPU_NATIVE_WEI_WALIGNED         (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x2Cu)
#define CDC_NPU_NATIVE_WEI_INCNTLIM         (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x04u)
#define CDC_NPU_NATIVE_WEI_INCNTSTEP        (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x08u)
#define CDC_NPU_NATIVE_V4_WEI_INCNTLIM      (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x00u)
#define CDC_NPU_NATIVE_V4_WEI_INCNTSTEP     (CDC_NPU_NATIVE_CFG_WEI_OFFSET + 0x04u)

#define CDC_NPU_NATIVE_ACT_XLIM             (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x14u)
#define CDC_NPU_NATIVE_ACT_XSTEP            (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x18u)
#define CDC_NPU_NATIVE_ACT_YLIM             (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x1Cu)
#define CDC_NPU_NATIVE_ACT_YSTEP            (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x20u)
#define CDC_NPU_NATIVE_ACT_CHLIM            (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x24u)
#define CDC_NPU_NATIVE_ACT_CHSTEP           (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x2Cu)
#define CDC_NPU_NATIVE_ACT_TIL_XLIM         (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x30u)
#define CDC_NPU_NATIVE_ACT_TIL_XSTEP        (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x34u)
#define CDC_NPU_NATIVE_ACT_TIL_YLIM         (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x38u)
#define CDC_NPU_NATIVE_ACT_TIL_YSTEP        (CDC_NPU_NATIVE_CFG_ACT_OFFSET + 0x3Cu)

#define CDC_NPU_NATIVE_NCONTEXTS            (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x00u)
#define CDC_NPU_NATIVE_TIL_CYLIM            (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x14u)
#define CDC_NPU_NATIVE_TIL_CYSTEP           (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x18u)
#define CDC_NPU_NATIVE_TIL_CKLIM            (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x1Cu)
#define CDC_NPU_NATIVE_TIL_CKSTEP           (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x20u)
#define CDC_NPU_NATIVE_INACTIVE_COLS        (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x24u)
#define CDC_NPU_NATIVE_PRELOAD_EN           (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x28u)
#define CDC_NPU_NATIVE_OUT_CXLIM            (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x04u)
#define CDC_NPU_NATIVE_OUT_CXSTEP           (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x08u)
#define CDC_NPU_NATIVE_OUT_CKLIM            (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x0Cu)
#define CDC_NPU_NATIVE_OUT_CKSTEP           (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x10u)
#define CDC_NPU_NATIVE_V4_OUT_CXLIM         (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x00u)
#define CDC_NPU_NATIVE_V4_OUT_CXSTEP        (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x04u)
#define CDC_NPU_NATIVE_V4_OUT_CKLIM         (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x08u)
#define CDC_NPU_NATIVE_V4_OUT_CKSTEP        (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x0Cu)
#define CDC_NPU_NATIVE_V4_OUT_TIL_CYLIM     (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x10u)
#define CDC_NPU_NATIVE_V4_OUT_TIL_CYSTEP    (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x14u)
#define CDC_NPU_NATIVE_V4_OUT_TIL_CKLIM     (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x18u)
#define CDC_NPU_NATIVE_V4_OUT_TIL_CKSTEP    (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x1Cu)
#define CDC_NPU_NATIVE_OUT_OBP_CFG_A        (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x20u)
#define CDC_NPU_NATIVE_OUT_REQUANT_SCALE_A  (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x24u)
#define CDC_NPU_NATIVE_OUT_REQUANT_SHIFT_A  (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x28u)
#define CDC_NPU_NATIVE_OUT_OBP_CFG_B        (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x30u)
#define CDC_NPU_NATIVE_OUT_REQUANT_SCALE_B  (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x34u)
#define CDC_NPU_NATIVE_OUT_REQUANT_SHIFT_B  (CDC_NPU_NATIVE_CFG_OUT_OFFSET + 0x38u)

#define CDC_NPU_NATIVE_IN_H                 (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x00u)
#define CDC_NPU_NATIVE_IN_W                 (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x04u)
#define CDC_NPU_NATIVE_IN_C                 (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x08u)
#define CDC_NPU_NATIVE_OUT_H                (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x0Cu)
#define CDC_NPU_NATIVE_OUT_W                (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x10u)
#define CDC_NPU_NATIVE_OUT_C                (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x14u)
#define CDC_NPU_NATIVE_KERNEL_H             (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x18u)
#define CDC_NPU_NATIVE_KERNEL_W             (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x1Cu)
#define CDC_NPU_NATIVE_STRIDE               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x20u)
#define CDC_NPU_NATIVE_PADDING              (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x24u)
#define CDC_NPU_NATIVE_DILATION             (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x28u)
#define CDC_NPU_NATIVE_DIL_PAT              (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x2Cu)
#define CDC_NPU_NATIVE_TILE_X               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x30u)
#define CDC_NPU_NATIVE_TILE_Y               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x34u)
#define CDC_NPU_NATIVE_TILE_K               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x38u)
#define CDC_NPU_NATIVE_TILE_C               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x3Cu)
#define CDC_NPU_NATIVE_X_USED               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x40u)
#define CDC_NPU_NATIVE_Y_USED               (CDC_NPU_NATIVE_CFG_LAYER_OFFSET + 0x44u)

/* Compact VP aliases for sparse V4.4 rich-instruction, OBP and RCE regions. */
#define CDC_NPU_VP_RICH_ALIAS_BASE          0x00010000u
#define CDC_NPU_VP_RICH_INST_LO_A           (CDC_NPU_VP_RICH_ALIAS_BASE + 0x300u)
#define CDC_NPU_VP_RICH_INST_HI_A           (CDC_NPU_VP_RICH_ALIAS_BASE + 0x304u)
#define CDC_NPU_VP_RICH_INST_LO_B           (CDC_NPU_VP_RICH_ALIAS_BASE + 0x308u)
#define CDC_NPU_VP_RICH_INST_HI_B           (CDC_NPU_VP_RICH_ALIAS_BASE + 0x30Cu)
#define CDC_NPU_VP_RICH_PUSH_A              (CDC_NPU_VP_RICH_ALIAS_BASE + 0x310u)
#define CDC_NPU_VP_RICH_PUSH_B              (CDC_NPU_VP_RICH_ALIAS_BASE + 0x314u)
#define CDC_NPU_VP_RICH_IN_ADDR             (CDC_NPU_VP_RICH_ALIAS_BASE + 0x400u)
#define CDC_NPU_VP_RICH_WEIGHT_ADDR         (CDC_NPU_VP_RICH_ALIAS_BASE + 0x404u)
#define CDC_NPU_VP_RICH_OUT_ADDR            (CDC_NPU_VP_RICH_ALIAS_BASE + 0x408u)
#define CDC_NPU_VP_RICH_BIAS_ADDR           (CDC_NPU_VP_RICH_ALIAS_BASE + 0x40Cu)
#define CDC_NPU_VP_RICH_M                   (CDC_NPU_VP_RICH_ALIAS_BASE + 0x410u)
#define CDC_NPU_VP_RICH_K                   (CDC_NPU_VP_RICH_ALIAS_BASE + 0x414u)
#define CDC_NPU_VP_RICH_N                   (CDC_NPU_VP_RICH_ALIAS_BASE + 0x418u)
#define CDC_NPU_VP_RICH_KERNEL_H            (CDC_NPU_VP_RICH_ALIAS_BASE + 0x41Cu)
#define CDC_NPU_VP_RICH_KERNEL_W            (CDC_NPU_VP_RICH_ALIAS_BASE + 0x420u)
#define CDC_NPU_VP_RICH_STRIDE              (CDC_NPU_VP_RICH_ALIAS_BASE + 0x424u)
#define CDC_NPU_VP_RICH_PADDING             (CDC_NPU_VP_RICH_ALIAS_BASE + 0x428u)
#define CDC_NPU_VP_RICH_ACT_TYPE            (CDC_NPU_VP_RICH_ALIAS_BASE + 0x42Cu)
#define CDC_NPU_VP_RICH_HAS_SKIP            (CDC_NPU_VP_RICH_ALIAS_BASE + 0x430u)
#define CDC_NPU_VP_RICH_SKIP_ADDR           (CDC_NPU_VP_RICH_ALIAS_BASE + 0x434u)
#define CDC_NPU_VP_RICH_IN_SCALE            (CDC_NPU_VP_RICH_ALIAS_BASE + 0x438u)
#define CDC_NPU_VP_RICH_WEIGHT_SCALE        (CDC_NPU_VP_RICH_ALIAS_BASE + 0x43Cu)
#define CDC_NPU_VP_RICH_OUT_SCALE           (CDC_NPU_VP_RICH_ALIAS_BASE + 0x440u)
#define CDC_NPU_VP_RICH_Q_GAMMA_A_ADDR      (CDC_NPU_VP_RICH_ALIAS_BASE + 0x444u)
#define CDC_NPU_VP_RICH_K_B_ADDR            (CDC_NPU_VP_RICH_ALIAS_BASE + 0x448u)
#define CDC_NPU_VP_RICH_V_BETA_ADDR         (CDC_NPU_VP_RICH_ALIAS_BASE + 0x44Cu)
#define CDC_NPU_VP_RICH_SEQ_LEN             (CDC_NPU_VP_RICH_ALIAS_BASE + 0x450u)
#define CDC_NPU_VP_RICH_HEADS_DIM_MODE      (CDC_NPU_VP_RICH_ALIAS_BASE + 0x454u)
#define CDC_NPU_VP_RICH_HEAD_DIM_EPS        (CDC_NPU_VP_RICH_ALIAS_BASE + 0x458u)
#define CDC_NPU_VP_RICH_ATTN_SCALE          (CDC_NPU_VP_RICH_ALIAS_BASE + 0x45Cu)
#define CDC_NPU_VP_RICH_SCALE_OUT           (CDC_NPU_VP_RICH_ALIAS_BASE + 0x460u)

#define CDC_NPU_VP_OBP_A_LUT_BASE           0x00020000u
#define CDC_NPU_VP_OBP_A_LUT_SIZE           0x00004000u
#define CDC_NPU_VP_OBP_A_BIAS_BASE          0x00024000u
#define CDC_NPU_VP_OBP_A_BIAS_SIZE          0x00000100u
#define CDC_NPU_VP_OBP_A_SCALE_BASE         0x00025000u
#define CDC_NPU_VP_OBP_A_SCALE_SIZE         0x00000100u
#define CDC_NPU_VP_OBP_A_SHIFT_BASE         0x00026000u
#define CDC_NPU_VP_OBP_A_SHIFT_SIZE         0x00000100u
#define CDC_NPU_VP_OBP_B_LUT_BASE           0x00028000u
#define CDC_NPU_VP_OBP_B_LUT_SIZE           0x00004000u
#define CDC_NPU_VP_OBP_B_BIAS_BASE          0x0002C000u
#define CDC_NPU_VP_OBP_B_BIAS_SIZE          0x00000100u
#define CDC_NPU_VP_OBP_B_SCALE_BASE         0x0002D000u
#define CDC_NPU_VP_OBP_B_SCALE_SIZE         0x00000100u
#define CDC_NPU_VP_OBP_B_SHIFT_BASE         0x0002E000u
#define CDC_NPU_VP_OBP_B_SHIFT_SIZE         0x00000100u
#define CDC_NPU_VP_RCE_A_EXP_BASE           0x00032000u
#define CDC_NPU_VP_RCE_A_EXP_SIZE           0x00000100u
#define CDC_NPU_VP_RCE_A_RECIP_BASE         0x00033000u
#define CDC_NPU_VP_RCE_A_RECIP_SIZE         0x00000200u
#define CDC_NPU_VP_RCE_A_RSQRT_BASE         0x00034000u
#define CDC_NPU_VP_RCE_A_RSQRT_SIZE         0x00000800u
#define CDC_NPU_VP_RCE_B_EXP_BASE           0x00035000u
#define CDC_NPU_VP_RCE_B_EXP_SIZE           0x00000100u
#define CDC_NPU_VP_RCE_B_RECIP_BASE         0x00036000u
#define CDC_NPU_VP_RCE_B_RECIP_SIZE         0x00000200u
#define CDC_NPU_VP_RCE_B_RSQRT_BASE         0x00037000u
#define CDC_NPU_VP_RCE_B_RSQRT_SIZE         0x00000800u

/* Simulation-only 64-bit performance counter ABI. */
#define CDC_NPU_PERF_EXEC_CYCLES_HI         0x1240u
#define CDC_NPU_PERF_STALL_CYCLES_HI        0x1244u
#define CDC_NPU_PERF_MAC_OPS_HI             0x1248u
#define CDC_NPU_PERF_ACTIVE_PE_CYCLES_HI    0x124Cu
#define CDC_NPU_PERF_TOTAL_PE_CYCLES_HI     0x1250u
#define CDC_NPU_PERF_TOTAL_CYCLES_HI        0x1254u
#define CDC_NPU_PERF_M_HI                   0x1258u
#define CDC_NPU_PERF_K_HI                   0x125Cu
#define CDC_NPU_PERF_N_HI                   0x1260u
#define CDC_NPU_PERF_SA_CYCLES_HI           0x1264u
#define CDC_NPU_PERF_OBP_CYCLES_HI          0x1268u
#define CDC_NPU_PERF_PROCESSING_CYCLES_HI   0x1300u
#define CDC_NPU_PERF_TRANSFER_CYCLES_HI     0x1304u
#define CDC_NPU_PERF_MAC_ENGINE_CYCLES_HI   0x1308u
#define CDC_NPU_PERF_DMA_ENGINE_CYCLES_HI   0x130Cu
#define CDC_NPU_PERF_ACTIVATION_ENGINE_CYCLES_HI 0x1310u
#define CDC_NPU_PERF_POOLING_ENGINE_CYCLES_HI 0x1314u
#define CDC_NPU_PERF_REDUCTION_ENGINE_CYCLES_HI 0x1318u
#define CDC_NPU_PERF_DDR_READ_BYTES_HI      0x131Cu
#define CDC_NPU_PERF_DDR_WRITE_BYTES_HI     0x1320u
#define CDC_NPU_PERF_DMA_READ_CYCLES_HI     0x1324u
#define CDC_NPU_PERF_DMA_WRITE_CYCLES_HI    0x1328u

#define CDC_NPU_CTRL_ENABLE         (1u << 0)
#define CDC_NPU_CTRL_START          (1u << 1)
#define CDC_NPU_CTRL_SOFT_RESET     (1u << 2)
#define CDC_NPU_CTRL_IRQ_EN         (1u << 3)

#define CDC_NPU_STATUS_BUSY         (1u << 0)
#define CDC_NPU_STATUS_DONE         (1u << 1)
#define CDC_NPU_STATUS_ERROR        (1u << 2)
#define CDC_NPU_STATUS_IDLE         (1u << 3)

#define CDC_NPU_IRQ_DONE            (1u << 0)
#define CDC_NPU_IRQ_ERROR           (1u << 1)

#define CDC_NPU_FORMAT_INT8_INT8_INT32 1u
#define CDC_NPU_FORMAT_INT8_INT8_INT8  2u
#define CDC_NPU_OP_GEMM                0u
#define CDC_NPU_CORE_ID_VALUE          0x53413432u

#define CDC_NPU_ERROR_NONE               0u
#define CDC_NPU_ERROR_DISABLED           1u
#define CDC_NPU_ERROR_BUSY               2u
#define CDC_NPU_ERROR_INVALID_DIMENSIONS 3u
#define CDC_NPU_ERROR_INVALID_FORMAT     4u
#define CDC_NPU_ERROR_INVALID_OPERATION  5u
#define CDC_NPU_ERROR_INVALID_ADDRESS    6u
#define CDC_NPU_ERROR_INVALID_SIZE       7u
#define CDC_NPU_ERROR_DMA_READ           8u
#define CDC_NPU_ERROR_DMA_WRITE          9u
#define CDC_NPU_ERROR_CORE_DEADLOCK      10u
#define CDC_NPU_ERROR_CORE_TIMEOUT       11u
#define CDC_NPU_ERROR_RESET_ABORTED      12u

#endif /* CDC_SOC_REGS_NPU_V4_H */
