#!/usr/bin/env python3
"""
Visualize YUV420 output of the SystemC ISP testbenches.

Mirrors the look-and-feel of the original `components/isp_tlm/visualize.py`
but is tuned for the SystemC streaming pipeline:
  - reads the two .yuv files generated by `tb_d65_pipeline`
    (`d65_pipeline.yuv` from SystemC, `d65_pipeline_golden.yuv` from C++)
  - accepts explicit `--input`, `--golden`, `--width`, `--height`
    arguments so you can reuse it for any future SystemC test
  - supports both planar YUV420 (Y..U..V) and NV12 (Y..UV..)
  - plots 3 panels: raw input (Bayer-coded) | golden | SystemC output
  - reports per-plane MSE between SystemC and golden

Usage:
  ./visualize.py                                    # default D65 outputs
  ./visualize.py --input <raw> --width 2688 --height 1520 \
                 --sc    path/to/d65_pipeline.yuv \
                 --golden path/to/d65_pipeline_golden.yuv \
                 --bit-depth 16 --pattern RGGB
"""

import argparse
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Default locations: <repo>/components/isp_tlm/systemc/output/
DEFAULT_OUTPUT_DIR = os.path.join(SCRIPT_DIR, "pipeline", "output")
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(SCRIPT_DIR)))  # CDC-VP/
DEFAULT_INPUT_RAW = os.path.join(
    REPO_ROOT, "components", "isp_tlm", "input", "D65_raw_2688x1520_5376.raw"
)
DEFAULT_SC_YUV    = os.path.join(DEFAULT_OUTPUT_DIR, "d65_pipeline.yuv")
DEFAULT_GOLD_YUV  = os.path.join(DEFAULT_OUTPUT_DIR, "d65_pipeline_golden.yuv")

try:
    import numpy as np
    import matplotlib.pyplot as plt
except ModuleNotFoundError as exc:
    print(
        f"Missing Python dependency: {exc.name}\n"
        "Install the visualization dependencies, for example:\n"
        "  sudo apt install python3-numpy python3-matplotlib\n"
        "or, if pip is available for python3:\n"
        "  python3 -m pip install numpy matplotlib",
        file=sys.stderr,
    )
    sys.exit(1)


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------
def read_raw_image(filepath, width, height, bit_depth=16):
    """Read a RAW Bayer file as a 2D array of 12/14/16-bit samples.

    The on-disk format for D65 is RAW16 little-endian; we interpret the
    samples as the configured `bit_depth`-bit values so the displayed
    brightness is correct regardless of the sensor range.
    """
    raw = np.fromfile(filepath, dtype=np.uint16)
    if raw.size != width * height:
        raise RuntimeError(
            f"RAW size mismatch: file has {raw.size} samples, "
            f"expected {width * height} for {width}x{height}"
        )
    img = raw.reshape((height, width)).astype(np.float32)
    # Normalize to [0, 1] using the configured bit depth.
    max_val = float((1 << bit_depth) - 1)
    return np.clip(img / max_val, 0.0, 1.0)


# ---------------------------------------------------------------------------
# YUV420 loaders. The pipeline emits NV12 (Y then interleaved UV).
# We also accept planar (Y then U then V) for legacy/external files.
# ---------------------------------------------------------------------------
def detect_yuv_layout(filepath, width, height):
    """Heuristic: if U and V interleave at even/odd offsets the file is NV12.

    We compare the mean of bytes at even offsets in the chroma region
    vs. at odd offsets; if they're similar the file is NV12. Otherwise
    assume planar.
    """
    data = np.fromfile(filepath, dtype=np.uint8)
    y_size = width * height
    chroma_w = (width + 1) // 2
    chroma_h = (height + 1) // 2
    chroma_size = chroma_w * chroma_h  # one chroma plane

    if data.size < y_size + 2 * chroma_size:
        return "planar"
    # In NV12, even/odd bytes in chroma region should both average ~128.
    # In planar, the first half is U (offset range), then V starts later;
    # the first chroma_size bytes will have one distribution and the
    # second chroma_size bytes another. Comparing the variance of the
    # whole first half vs the split halves distinguishes them.
    chroma = data[y_size:y_size + 2 * chroma_size]
    even = chroma[0::2]
    odd = chroma[1::2]
    if abs(even.mean() - odd.mean()) < 8.0:
        return "nv12"
    return "planar"


def read_yuv420_nv12(filepath, width, height):
    """Read NV12 (semi-planar: Y + interleaved UV) and return (Y, U, V)."""
    data = np.fromfile(filepath, dtype=np.uint8)
    y_size = width * height
    chroma_w = (width + 1) // 2
    chroma_h = (height + 1) // 2
    chroma_size = chroma_w * chroma_h

    if data.size < y_size + 2 * chroma_size:
        raise RuntimeError(
            f"YUV file size {data.size} smaller than expected "
            f"{y_size + 2 * chroma_size} for {width}x{height}"
        )

    Y = data[0:y_size].reshape((height, width))
    uv = data[y_size:y_size + 2 * chroma_size]
    U = uv[0::2].reshape((chroma_h, chroma_w))
    V = uv[1::2].reshape((chroma_h, chroma_w))
    return Y, U, V


def read_yuv420_planar(filepath, width, height):
    """Read planar YUV420 (Y then U then V) and return (Y, U, V) uint8 arrays.

    Planar layout:
      - Y plane: width * height bytes
      - U plane: chroma_w * chroma_h bytes
      - V plane: chroma_w * chroma_h bytes
    """
    data = np.fromfile(filepath, dtype=np.uint8)
    y_size = width * height
    chroma_w = (width + 1) // 2
    chroma_h = (height + 1) // 2
    chroma_size = chroma_w * chroma_h

    if data.size < y_size + 2 * chroma_size:
        raise RuntimeError(
            f"YUV file size {data.size} smaller than expected "
            f"{y_size + 2 * chroma_size} for {width}x{height}"
        )

    Y = data[0:y_size].reshape((height, width))
    U = data[y_size:y_size + chroma_size].reshape((chroma_h, chroma_w))
    V = data[y_size + chroma_size:y_size + 2 * chroma_size].reshape((chroma_h, chroma_w))
    return Y, U, V


def read_yuv420(filepath, width, height, layout="auto"):
    """Dispatch to NV12 or planar based on `layout`.

    `layout='auto'` runs `detect_yuv_layout` on the file.
    """
    if layout == "auto":
        layout = detect_yuv_layout(filepath, width, height)
        print(f"  (auto-detected layout: {layout})")
    if layout == "nv12":
        return read_yuv420_nv12(filepath, width, height)
    return read_yuv420_planar(filepath, width, height)


def yuv420_to_rgb(Y, U, V, limited_range=True):
    """BT.601 YUV420 -> RGB (0..1 float).

    `limited_range=True`  treats the YUV as the standard "MPEG" limited range
                          (Y in [16,235], U/V in [16,240]), which is what the
                          ISP pipeline emits. This matches the convention
                          used by ffplay and most viewers.
    """
    chroma_h, chroma_w = U.shape
    h, w = Y.shape
    # Upsample chroma to full resolution using nearest-neighbor (replicate 2x2).
    U_up = np.repeat(np.repeat(U, 2, axis=0), 2, axis=1)[:h, :w].astype(np.float32)
    V_up = np.repeat(np.repeat(V, 2, axis=0), 2, axis=1)[:h, :w].astype(np.float32)
    Y_f = Y.astype(np.float32)
    U_f = U_up - 128.0
    V_f = V_up - 128.0

    if limited_range:
        Y_f = (Y_f - 16.0) * (255.0 / 219.0)

    R = Y_f + 1.402 * V_f
    G = Y_f - 0.344136 * U_f - 0.714136 * V_f
    B = Y_f + 1.772 * U_f

    RGB = np.stack([R, G, B], axis=-1)
    return np.clip(RGB, 0, 255) / 255.0


# ---------------------------------------------------------------------------
# Bayer visualization (copied from the reference visualize.py)
# ---------------------------------------------------------------------------
def visualize_bayer_raw(bayer, pattern="RGGB"):
    """Color-coded CFA mask so the Bayer grid is visible at any zoom."""
    h, w = bayer.shape
    brightness = bayer.astype(np.float32)  # already in [0, 1]

    masks = {
        "RGGB": (("r",  0, 0), ("gr", 0, 1), ("gb", 1, 0), ("b",  1, 1)),
        "BGGR": (("b",  0, 0), ("gb", 0, 1), ("gr", 1, 0), ("r",  1, 1)),
        "GRBG": (("gr", 0, 0), ("r",  0, 1), ("b",  1, 0), ("gb", 1, 1)),
        "GBRG": (("gb", 0, 0), ("b",  0, 1), ("r",  1, 0), ("gr", 1, 1)),
    }
    pat = masks.get(pattern.upper(), masks["RGGB"])
    masks_bool = {}
    for label, ry, rx in pat:
        m = np.zeros((h, w), dtype=bool)
        m[ry::2, rx::2] = True
        masks_bool[label] = m

    rgb = np.zeros((h, w, 3), dtype=np.float32)
    base = np.zeros((h, w, 3), dtype=np.float32)
    for label, idx in (("r", 0), ("b", 2)):
        m = masks_bool[label]
        rgb[..., idx] = np.where(m, brightness * 1.0, 0.0)
        base_color = np.zeros(3, dtype=np.float32); base_color[idx] = 0.4
        base[m] = base_color
    for label in ("gr", "gb"):
        m = masks_bool[label]
        rgb[..., 1] = np.where(m, np.maximum(rgb[..., 1], brightness), rgb[..., 1])
        base_color = np.zeros(3, dtype=np.float32); base_color[1] = 0.4
        base[m] = base_color

    return np.clip(base * 0.7 + rgb * 0.3, 0, 1)


# ---------------------------------------------------------------------------
# MSE helpers
# ---------------------------------------------------------------------------
def per_plane_mse(a_path, b_path, width, height, layout="auto"):
    """Compute MSE per plane (Y, U, V) between two YUV420 files of identical size."""
    aY, aU, aV = read_yuv420(a_path, width, height, layout)
    bY, bU, bV = read_yuv420(b_path, width, height, layout)
    def mse(x, y):
        d = x.astype(np.float64) - y.astype(np.float64)
        return float((d * d).mean())
    return {
        "Y": mse(aY, bY),
        "U": mse(aU, bU),
        "V": mse(aV, bV),
        "all": mse(
            np.concatenate([aY.ravel(), aU.ravel(), aV.ravel()]),
            np.concatenate([bY.ravel(), bU.ravel(), bV.ravel()]),
        ),
    }


# ---------------------------------------------------------------------------
# Metadata sidecar (optional)
# ---------------------------------------------------------------------------
def read_metadata(yuv_path):
    p = yuv_path + ".json"
    if os.path.exists(p):
        try:
            with open(p, "r") as f:
                return json.load(f)
        except Exception as e:
            print(f"Warning: could not read metadata {p}: {e}")
    return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    p.add_argument("--input",    default=DEFAULT_INPUT_RAW, help="Path to input RAW Bayer file")
    p.add_argument("--sc",       default=DEFAULT_SC_YUV,    help="Path to SystemC-produced YUV file")
    p.add_argument("--golden",   default=DEFAULT_GOLD_YUV,  help="Path to golden YUV file (optional)")
    p.add_argument("--width",    type=int, default=2688)
    p.add_argument("--height",   type=int, default=1520)
    # Output size (after scale). If different from width/height we'll
    # auto-detect from the .yuv file size when the metadata sidecar is missing.
    p.add_argument("--out-width",  type=int, default=None)
    p.add_argument("--out-height", type=int, default=None)
    p.add_argument("--bit-depth",  type=int, default=16,   help="Sensor bit depth (D65=16)")
    p.add_argument("--pattern",    default="RGGB")
    p.add_argument("--layout",     choices=["auto", "planar", "nv12"], default="auto",
                   help="YUV420 file layout. Default: auto-detect "
                        "(pipeline emits NV12; use 'planar' for legacy files)")
    p.add_argument("--out",        default=None, help="Where to save the comparison figure (.jpg)")
    return p.parse_args()


def auto_out_dims_from_file(yuv_path):
    """Infer (width, height) of a planar YUV420 file from its size.

    For YUV420 planar: total = W*H + 2 * ((W+1)//2) * ((H+1)//2).
    The most common D65 pipeline output is 2688x1520 -> 672x380.
    """
    if not yuv_path or not os.path.exists(yuv_path):
        return None
    size = os.path.getsize(yuv_path)
    # Search a small set of common resolutions.
    candidates = [
        (672, 380), (768, 432), (1280, 720), (1920, 1080),
        (2688, 1520), (2592, 1536),
    ]
    for w, h in candidates:
        y_size = w * h
        c_w = (w + 1) // 2
        c_h = (h + 1) // 2
        expected = y_size + 2 * c_w * c_h
        if expected == size:
            return w, h
    return None


def main():
    args = parse_args()
    input_raw = args.input
    sc_path   = args.sc
    gold_path = args.golden

    # Pull output size from metadata sidecar or auto-detect from file size.
    out_w = args.out_width
    out_h = args.out_height
    meta  = read_metadata(sc_path)
    if meta is not None:
        out_w = out_w or meta.get("width")
        out_h = out_h or meta.get("height")
        print(f"Loaded metadata from {sc_path}.json")
    if (out_w is None or out_h is None) and sc_path and os.path.exists(sc_path):
        detected = auto_out_dims_from_file(sc_path)
        if detected is not None:
            out_w, out_h = detected
            print(f"Auto-detected output size from file: {out_w}x{out_h}")
    if out_w is None or out_h is None:
        out_w, out_h = args.width, args.height
        print(f"Note: using --width/--height for output ({out_w}x{out_h})")

    # --- Load input RAW (optional, for the side-by-side preview) ---------
    bayer_rgb = None
    if input_raw and os.path.exists(input_raw):
        print(f"Reading RAW input: {input_raw} ({args.width}x{args.height}, "
              f"{args.bit_depth}-bit, {args.pattern})")
        bayer = read_raw_image(input_raw, args.width, args.height, args.bit_depth)
        bayer_rgb = visualize_bayer_raw(bayer, pattern=args.pattern)
    else:
        print(f"Skipping input RAW (not found): {input_raw}")

    # --- Load SystemC output ---------------------------------------------
    sc_rgb = None
    if sc_path and os.path.exists(sc_path):
        print(f"Reading SystemC YUV: {sc_path} ({out_w}x{out_h})")
        Y, U, V = read_yuv420(sc_path, out_w, out_h, args.layout)
        sc_rgb = yuv420_to_rgb(Y, U, V)
    else:
        print(f"SystemC YUV not found: {sc_path}")

    # --- Load golden output (optional) -----------------------------------
    gold_rgb = None
    if gold_path and os.path.exists(gold_path):
        print(f"Reading golden YUV:  {gold_path} ({out_w}x{out_h})")
        Y, U, V = read_yuv420(gold_path, out_w, out_h, args.layout)
        gold_rgb = yuv420_to_rgb(Y, U, V)

    # --- MSE report -------------------------------------------------------
    mse_report = None
    if sc_rgb is not None and gold_rgb is not None:
        try:
            mse_report = per_plane_mse(sc_path, gold_path, out_w, out_h, args.layout)
        except Exception as e:
            print(f"Could not compute MSE: {e}")

    # --- Plotting ---------------------------------------------------------
    n_cols = 1 + (1 if gold_rgb is not None else 0) + (1 if sc_rgb is not None else 0)
    if bayer_rgb is not None:
        n_cols += 1

    fig, axes = plt.subplots(1, n_cols, figsize=(5 * n_cols, 5))
    if n_cols == 1:
        axes = [axes]

    idx = 0
    if bayer_rgb is not None:
        axes[idx].imshow(bayer_rgb)
        axes[idx].set_title(f"Input RAW ({args.pattern})\n{args.width}x{args.height}")
        axes[idx].axis("off")
        idx += 1

    if gold_rgb is not None:
        axes[idx].imshow(gold_rgb)
        axes[idx].set_title(f"Golden (C++ isp_pipeline)\n{out_w}x{out_h}")
        axes[idx].axis("off")
        idx += 1

    if sc_rgb is not None:
        axes[idx].imshow(sc_rgb)
        axes[idx].set_title(f"SystemC (sc_isp_pipeline)\n{out_w}x{out_h}")
        axes[idx].axis("off")
        idx += 1

    plt.tight_layout()

    out_path = args.out or os.path.join(DEFAULT_OUTPUT_DIR, "d65_pipeline_compare.jpg")
    plt.savefig(out_path, dpi=120)
    print(f"\nSaved comparison figure to {out_path}")
    try:
        if sc_rgb is not None:
            plt.imsave(os.path.join(DEFAULT_OUTPUT_DIR, "d65_pipeline_sc.jpg"), sc_rgb)
        if gold_rgb is not None:
            plt.imsave(os.path.join(DEFAULT_OUTPUT_DIR, "d65_pipeline_golden.jpg"), gold_rgb)
        if bayer_rgb is not None:
            plt.imsave(os.path.join(DEFAULT_OUTPUT_DIR, "d65_pipeline_input.jpg"), bayer_rgb)
    except Exception as e:
        print(f"Warning: could not save individual JPEGs: {e}")

    # --- Print stats ------------------------------------------------------
    if mse_report is not None:
        print("\nSystemC vs Golden (YUV420 MSE):")
        for k, v in mse_report.items():
            print(f"  {k:>3}: {v:.4f}")

    if sc_rgb is not None:
        print("\nSystemC output statistics (after BT.601 -> RGB):")
        for k, name in enumerate(("R", "G", "B")):
            chan = (sc_rgb[..., k] * 255).astype(np.int32)
            print(f"  {name}: min={chan.min()}, max={chan.max()}, mean={chan.mean():.1f}")


if __name__ == "__main__":
    main()