# Keep the library usable by both add_subdirectory and installed consumers.
set(_h264_cdc_export OFF)
if(CMAKE_PROJECT_NAME STREQUAL "cdc-vp")
  set(_h264_cdc_export ON)
endif()
option(H264_USE_CDC_EXPORT "Join CDC-VP's parent-owned export set" ${_h264_cdc_export})
set(_h264_export h264-targets)
if(H264_USE_CDC_EXPORT)
  set(_h264_export cdc-components-targets)
endif()
set_target_properties(h264_top PROPERTIES EXPORT_NAME h264_tlm)
foreach(pair "h264_shared|interfaces" "h264_sync|synchronization"
             "h264_control|control" "h264_dma_transport|top" "h264_top|top"
             "h264_pipeline_stub|tests/support/stubs")
  string(REPLACE "|" ";" parts "${pair}")
  list(GET parts 0 lib)
  list(GET parts 1 dir)
  if(TARGET ${lib})
    set(_h264_headers "${CMAKE_CURRENT_SOURCE_DIR}/${dir}/include")
    # Preserve flattened module headers while keeping the public include API.
    if((lib STREQUAL "h264_control")
       AND NOT EXISTS "${_h264_headers}/h264")
      set(_h264_namespace control)
      set(_h264_public "${CMAKE_CURRENT_BINARY_DIR}/public_headers/${lib}")
      file(GLOB _h264_flat CONFIGURE_DEPENDS "${_h264_headers}/*.h")
      foreach(header IN LISTS _h264_flat)
        get_filename_component(name "${header}" NAME)
        configure_file("${header}" "${_h264_public}/h264/${_h264_namespace}/${name}" COPYONLY)
      endforeach()
      install(FILES ${_h264_flat} DESTINATION "include/h264/${_h264_namespace}")
      set(_h264_headers "${_h264_public}")
      target_include_directories(${lib} PRIVATE "${_h264_public}")
    else()
      install(DIRECTORY "${dir}/include/" DESTINATION include)
    endif()
    set_property(TARGET ${lib} PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "$<BUILD_INTERFACE:${_h264_headers}>;$<INSTALL_INTERFACE:include>")
    install(TARGETS ${lib} EXPORT ${_h264_export}
      ARCHIVE DESTINATION lib LIBRARY DESTINATION lib RUNTIME DESTINATION bin)
  endif()
endforeach()
install(TARGETS h264_dma h264_dma_tlm EXPORT ${_h264_export} ARCHIVE DESTINATION lib)
install(FILES dma_subsystems/tlm/include/h264_dma_tlm.h DESTINATION include/h264/dma)
install(DIRECTORY dma_subsystems/common dma_subsystems/dma dma_subsystems/mem DESTINATION include/h264/dma FILES_MATCHING PATTERN "*.h")
if(NOT H264_USE_CDC_EXPORT)
  install(EXPORT h264-targets NAMESPACE cdc::components::
    DESTINATION lib/cmake/h264-vp)
  install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/cmake/h264-vp-config.cmake"
    DESTINATION lib/cmake/h264-vp)
endif()
