// The C firmware header must match the model's C++ register definitions.
// Every comparison is a static_assert: a drift fails the build of this test.
#include "dma/fx1_dma_regs.h"
#include "dma/registers.h"
#include <iostream>

namespace r = fx1::dma::reg;

static_assert(FX1_DMA_CHANNEL_COUNT == r::CHANNEL_COUNT, "CHANNEL_COUNT");
static_assert(FX1_DMA_CHANNEL_STRIDE == r::CHANNEL_STRIDE, "CHANNEL_STRIDE");
static_assert(FX1_DMA_FIFO_BYTES == r::FIFO_BYTES, "FIFO_BYTES");
static_assert(FX1_DMA_MAX_BURST_BEATS == r::MAX_BURST_BEATS, "MAX_BURST_BEATS");
static_assert(FX1_DMA_MAX_TRANSFER == (1u << r::TRANSFER_SIZE_WIDTH) - 1, "MAX_TRANSFER");
static_assert(FX1_DMA_REGISTER_BYTES == r::REGISTER_BYTES, "REGISTER_BYTES");
static_assert(FX1_DMA_AXI_MASTER_ID == r::AXI_MASTER_ID, "AXI_MASTER_ID");
static_assert(FX1_DMA_CH(3, FX1_DMA_CH_ENABLE) == r::channel(3, r::CH_ENABLE), "FX1_DMA_CH");

static_assert(FX1_DMA_CH_CMD_READ_ADDR == r::CH_CMD_READ_ADDR, "CH_CMD_READ_ADDR");
static_assert(FX1_DMA_CH_CMD_WRITE_ADDR == r::CH_CMD_WRITE_ADDR, "CH_CMD_WRITE_ADDR");
static_assert(FX1_DMA_CH_CMD_TRANSFER_SIZE == r::CH_CMD_TRANSFER_SIZE, "CH_CMD_TRANSFER_SIZE");
static_assert(FX1_DMA_CH_CMD_CONTROL == r::CH_CMD_CONTROL, "CH_CMD_CONTROL");
static_assert(FX1_DMA_CH_READ_CONFIG == r::CH_READ_CONFIG, "CH_READ_CONFIG");
static_assert(FX1_DMA_CH_WRITE_CONFIG == r::CH_WRITE_CONFIG, "CH_WRITE_CONFIG");
static_assert(FX1_DMA_CH_MODE_CONFIG == r::CH_MODE_CONFIG, "CH_MODE_CONFIG");
static_assert(FX1_DMA_CH_SCHEDULE_CONFIG == r::CH_SCHEDULE_CONFIG, "CH_SCHEDULE_CONFIG");
static_assert(FX1_DMA_CH_PERIPHERAL_CONFIG == r::CH_PERIPHERAL_CONFIG, "CH_PERIPHERAL_CONFIG");
static_assert(FX1_DMA_CH_AXI_ATTR_REG == r::CH_AXI_ATTR_REG, "CH_AXI_ATTR_REG");
static_assert(FX1_DMA_CH_RESTRICTION_STATUS == r::CH_RESTRICTION_STATUS, "CH_RESTRICTION_STATUS");
static_assert(FX1_DMA_CH_READ_OFFSET_STATUS == r::CH_READ_OFFSET_STATUS, "CH_READ_OFFSET_STATUS");
static_assert(FX1_DMA_CH_WRITE_OFFSET_STATUS == r::CH_WRITE_OFFSET_STATUS, "CH_WRITE_OFFSET_STATUS");
static_assert(FX1_DMA_CH_FIFO_STATUS == r::CH_FIFO_STATUS, "CH_FIFO_STATUS");
static_assert(FX1_DMA_CH_OUTSTANDING_STATUS == r::CH_OUTSTANDING_STATUS, "CH_OUTSTANDING_STATUS");
static_assert(FX1_DMA_CH_ENABLE == r::CH_ENABLE, "CH_ENABLE");
static_assert(FX1_DMA_CH_START == r::CH_START, "CH_START");
static_assert(FX1_DMA_CH_ACTIVE_STATUS == r::CH_ACTIVE_STATUS, "CH_ACTIVE_STATUS");
static_assert(FX1_DMA_CH_TRANSFER_COUNT == r::CH_TRANSFER_COUNT, "CH_TRANSFER_COUNT");
static_assert(FX1_DMA_CH_INTERRUPT_RAW_STATUS == r::CH_INTERRUPT_RAW_STATUS, "CH_INTERRUPT_RAW_STATUS");
static_assert(FX1_DMA_CH_INTERRUPT_CLEAR == r::CH_INTERRUPT_CLEAR, "CH_INTERRUPT_CLEAR");
static_assert(FX1_DMA_CH_INTERRUPT_ENABLE == r::CH_INTERRUPT_ENABLE, "CH_INTERRUPT_ENABLE");
static_assert(FX1_DMA_CH_INTERRUPT_STATUS == r::CH_INTERRUPT_STATUS, "CH_INTERRUPT_STATUS");

static_assert(FX1_DMA_CORE_STATUS == r::CORE_STATUS, "CORE_STATUS");
static_assert(FX1_DMA_CORE_JOINT_CONFIG == r::CORE_JOINT_CONFIG, "CORE_JOINT_CONFIG");
static_assert(FX1_DMA_CORE_PRIORITY_CONFIG == r::CORE_PRIORITY_CONFIG, "CORE_PRIORITY_CONFIG");
static_assert(FX1_DMA_CORE_CLOCK_DIVIDER == r::CORE_CLOCK_DIVIDER, "CORE_CLOCK_DIVIDER");
static_assert(FX1_DMA_CORE_CHANNEL_START == r::CORE_CHANNEL_START, "CORE_CHANNEL_START");
static_assert(FX1_DMA_PERIPHERAL_RX_REQUEST == r::PERIPHERAL_RX_REQUEST, "PERIPHERAL_RX_REQUEST");
static_assert(FX1_DMA_PERIPHERAL_TX_REQUEST == r::PERIPHERAL_TX_REQUEST, "PERIPHERAL_TX_REQUEST");
static_assert(FX1_DMA_CORE_IDLE_STATUS == r::CORE_IDLE_STATUS, "CORE_IDLE_STATUS");
static_assert(FX1_DMA_DESIGN_CAPABILITY_STATUS == r::DESIGN_CAPABILITY_STATUS, "DESIGN_CAPABILITY_STATUS");
static_assert(FX1_DMA_CORE_CAPABILITY_STATUS0 == r::CORE_CAPABILITY_STATUS0, "CORE_CAPABILITY_STATUS0");
static_assert(FX1_DMA_CORE_CAPABILITY_STATUS1 == r::CORE_CAPABILITY_STATUS1, "CORE_CAPABILITY_STATUS1");

static_assert(FX1_DMA_CONFIG_RESET == r::CONFIG_RESET, "CONFIG_RESET");
static_assert(FX1_DMA_CONFIG_MASK == r::CONFIG_MASK, "CONFIG_MASK");
static_assert(FX1_DMA_PERIPHERAL_MASK == r::PERIPHERAL_MASK, "PERIPHERAL_MASK");
static_assert(FX1_DMA_ATTR_MASK == r::ATTR_MASK, "ATTR_MASK");
static_assert(FX1_DMA_MODE_MASK == r::MODE_MASK, "MODE_MASK");
static_assert(FX1_DMA_TRANSFER_SIZE_MASK == r::TRANSFER_SIZE_MASK, "TRANSFER_SIZE_MASK");
static_assert(FX1_DMA_INTERRUPT_MASK == r::INTERRUPT_MASK, "INTERRUPT_MASK");
static_assert(FX1_DMA_CAPABILITY0 == r::CAPABILITY0, "CAPABILITY0");
static_assert(FX1_DMA_CMD_SET_INT == r::CMD_SET_INT, "CMD_SET_INT");
static_assert(FX1_DMA_CMD_LAST == r::CMD_LAST, "CMD_LAST");
static_assert(FX1_DMA_ADDRESS_INCREMENT == r::ADDRESS_INCREMENT, "ADDRESS_INCREMENT");
static_assert(FX1_DMA_OUTSTANDING_ENABLE == r::OUTSTANDING_ENABLE, "OUTSTANDING_ENABLE");
// Field helpers stay inside the writable masks.
static_assert((FX1_DMA_ADDRESS_INCREMENT | FX1_DMA_OUTSTANDING_ENABLE | FX1_DMA_CFG_PENDING(15) |
               FX1_DMA_CFG_TOKENS(63) | FX1_DMA_CFG_BURST_BYTES(127)) == FX1_DMA_CONFIG_MASK,
              "config field helpers cover CONFIG_MASK exactly");
static_assert((FX1_DMA_PERIPH_READ(31) | FX1_DMA_PERIPH_READ_DELAY(7) | FX1_DMA_PERIPH_WRITE(31) |
               FX1_DMA_PERIPH_WRITE_DELAY(7)) == FX1_DMA_PERIPHERAL_MASK,
              "peripheral field helpers cover PERIPHERAL_MASK exactly");
static_assert((FX1_DMA_MODE_SWAP_16 | FX1_DMA_MODE_SWAP_32) == FX1_DMA_MODE_MASK, "swap encodings");

static_assert(FX1_DMA_INT_COMMAND_COMPLETE == r::COMMAND_COMPLETE, "COMMAND_COMPLETE");
static_assert(FX1_DMA_INT_READ_SLVERR == r::READ_SLVERR, "READ_SLVERR");
static_assert(FX1_DMA_INT_WRITE_SLVERR == r::WRITE_SLVERR, "WRITE_SLVERR");
static_assert(FX1_DMA_INT_READ_DECERR == r::READ_DECERR, "READ_DECERR");
static_assert(FX1_DMA_INT_WRITE_DECERR == r::WRITE_DECERR, "WRITE_DECERR");
static_assert(FX1_DMA_INT_FIFO_OVERFLOW == r::FIFO_OVERFLOW, "FIFO_OVERFLOW");
static_assert(FX1_DMA_INT_FIFO_UNDERFLOW == r::FIFO_UNDERFLOW, "FIFO_UNDERFLOW");
static_assert(FX1_DMA_INT_READ_DATA_TIMEOUT == r::READ_DATA_TIMEOUT, "READ_DATA_TIMEOUT");
static_assert(FX1_DMA_INT_READ_ADDRESS_TIMEOUT == r::READ_ADDRESS_TIMEOUT, "READ_ADDRESS_TIMEOUT");
static_assert(FX1_DMA_INT_WRITE_RESPONSE_TIMEOUT == r::WRITE_RESPONSE_TIMEOUT, "WRITE_RESPONSE_TIMEOUT");
static_assert(FX1_DMA_INT_WRITE_DATA_TIMEOUT == r::WRITE_DATA_TIMEOUT, "WRITE_DATA_TIMEOUT");
static_assert(FX1_DMA_INT_WRITE_ADDRESS_TIMEOUT == r::WRITE_ADDRESS_TIMEOUT, "WRITE_ADDRESS_TIMEOUT");
static_assert(FX1_DMA_INT_WATCHDOG_TIMEOUT == r::WATCHDOG_TIMEOUT, "WATCHDOG_TIMEOUT");
static_assert((FX1_DMA_INT_WATCHDOG_TIMEOUT << 1) - 1 == FX1_DMA_INTERRUPT_MASK, "13 interrupt bits");

int main() {
    std::cout << "fx1_dma_regs.h matches registers.h\n";
    return 0;
}
