#include "posi.h"
#include "prei.h"
#include <algorithm>
#include <cstdint>
#include <limits>
#include <numeric>

namespace cdc::components {

namespace {

int abs_int(int value)
{
    return value < 0 ? -value : value;
}

std::uint8_t clamp_u8(int value)
{
    return static_cast<std::uint8_t>(std::clamp(value, 0, 255));
}

std::uint32_t clamp_cost_u32(std::uint64_t value)
{
    return value > std::numeric_limits<std::uint32_t>::max()
               ? std::numeric_limits<std::uint32_t>::max()
               : static_cast<std::uint32_t>(value);
}

} // namespace

prediction_result posi::run(const frame& input,
                            const block& region) const
{
    prei temp_prei;
    prei_result hint = temp_prei.run(input, region);

    frame empty_reconstructed;
    return run(input, empty_reconstructed, region, hint, INIT_QP);
}

prediction_result posi::run(const frame& input,
                            const frame& reconstructed,
                            const block& region,
                            const prei_result& prei_info,
                            std::uint32_t qp) const
{
    if (input.empty() || region.area() == 0 || !prei_info.valid) {
        return prediction_result::invalid();
    }

    prediction_result best = prediction_result::invalid();
    std::uint32_t best_cost = std::numeric_limits<std::uint32_t>::max();

    for (const prei_mode_entry& entry : prei_info.mode_entries) {
        if (!entry.valid) {
            continue;
        }

        // POSI normally evaluates the CU entries generated by PREI.
        // If the PREI entry is not exactly the requested region, still evaluate
        // that CU because it represents the mode RAM entry from PREI.
        const block& eval_region = entry.cu.area() != 0 ? entry.cu : region;

        for (const prei_mode_candidate& candidate : entry.candidates) {
            if (!candidate.valid) {
                continue;
            }

            prediction_result result =
                evaluate_candidate(input,
                                   reconstructed,
                                   eval_region,
                                   entry,
                                   candidate,
                                   qp);

            if (result.valid && result.cost < best_cost) {
                best_cost = result.cost;
                best = std::move(result);
            }
        }
    }

    // Fallback path if PREI did not provide full candidate list.
    if (!best.valid && prei_info.best_intra_hint.valid) {
        prei_mode_entry entry;
        entry.valid = true;
        entry.cu = region;
        entry.best_mode = prei_info.best_intra_hint.intra_mode;
        entry.best_mode_index = static_cast<std::uint32_t>(prei_info.best_intra_hint.intra_mode);

        prei_mode_candidate candidate;
        candidate.valid = true;
        candidate.mode_index = entry.best_mode_index;
        candidate.mapped_mode = entry.best_mode;
        candidate.cost = prei_info.best_intra_hint.cost;

        best = evaluate_candidate(input,
                                  reconstructed,
                                  region,
                                  entry,
                                  candidate,
                                  qp);
    }

    return best;
}

prediction_result posi::evaluate_candidate(const frame& input,
                                           const frame& reconstructed,
                                           const block& region,
                                           const prei_mode_entry& mode_entry,
                                           const prei_mode_candidate& candidate,
                                           std::uint32_t qp) const
{
    (void)mode_entry;

    std::vector<std::uint8_t> predicted =
        generate_prediction(input, reconstructed, region, candidate.mode_index);

    std::vector<std::int16_t> residual =
        compute_residual(input, region, predicted);

    const std::uint32_t distortion =
        compute_satd_like_cost(residual, region);

    const partition_mode partition =
        decide_partition(region, distortion);

    const std::uint32_t rate =
        estimate_rate(candidate.mode_index, partition, region);

    const std::uint32_t lambda = 1u + qp / 6u;

    const std::uint32_t cost =
        clamp_cost_u32(static_cast<std::uint64_t>(distortion) +
                       static_cast<std::uint64_t>(lambda) * rate);

    prediction_result result = prediction_result::make_intra(
        cost,
        map_intra_mode(candidate.mode_index),
        partition,
        qp
    );

    result.valid = true;
    result.rate = rate;
    result.distortion = distortion;
    result.predicted_luma = std::move(predicted);
    result.residual_luma = std::move(residual);

    return result;
}

std::vector<std::uint8_t> posi::generate_prediction(const frame& input,
                                                    const frame& reconstructed,
                                                    const block& region,
                                                    std::uint32_t mode_index) const
{
    std::vector<std::uint8_t> predicted;
    predicted.reserve(region.area());

    for (std::uint32_t y = 0; y < region.height; ++y) {
        for (std::uint32_t x = 0; x < region.width; ++x) {
            predicted.push_back(
                predict_sample(input, reconstructed, region, x, y, mode_index)
            );
        }
    }

    return predicted;
}

std::uint8_t posi::predict_sample(const frame& input,
                                  const frame& reconstructed,
                                  const block& region,
                                  std::uint32_t local_x,
                                  std::uint32_t local_y,
                                  std::uint32_t mode_index) const
{
    if (mode_index == INTRA_PLANAR_MODE) {
        return predict_planar(input, reconstructed, region, local_x, local_y);
    }

    if (mode_index == INTRA_DC_MODE) {
        return predict_dc(input, reconstructed, region);
    }

    return predict_angular(input, reconstructed, region, local_x, local_y, mode_index);
}

std::uint8_t posi::predict_planar(const frame& input,
                                  const frame& reconstructed,
                                  const block& region,
                                  std::uint32_t local_x,
                                  std::uint32_t local_y) const
{
    const int x = static_cast<int>(region.x + local_x);
    const int y = static_cast<int>(region.y + local_y);

    const int left =
        get_reference_luma(input, reconstructed, static_cast<int>(region.x) - 1, y);

    const int top =
        get_reference_luma(input, reconstructed, x, static_cast<int>(region.y) - 1);

    const int top_right =
        get_reference_luma(input,
                           reconstructed,
                           static_cast<int>(region.x + region.width),
                           static_cast<int>(region.y) - 1);

    const int bottom_left =
        get_reference_luma(input,
                           reconstructed,
                           static_cast<int>(region.x) - 1,
                           static_cast<int>(region.y + region.height));

    const int width = static_cast<int>(region.width);
    const int height = static_cast<int>(region.height);

    const int lx = static_cast<int>(local_x);
    const int ly = static_cast<int>(local_y);

    const int hor =
        (width - 1 - lx) * left + (lx + 1) * top_right;

    const int ver =
        (height - 1 - ly) * top + (ly + 1) * bottom_left;

    const int denom = std::max(1, width + height);
    return clamp_u8((hor + ver + denom / 2) / denom);
}

std::uint8_t posi::predict_dc(const frame& input,
                              const frame& reconstructed,
                              const block& region) const
{
    std::uint32_t sum = 0;
    std::uint32_t count = 0;

    if (region.y > 0) {
        for (std::uint32_t x = 0; x < region.width; ++x) {
            sum += get_reference_luma(input,
                                      reconstructed,
                                      static_cast<int>(region.x + x),
                                      static_cast<int>(region.y) - 1);
            ++count;
        }
    }

    if (region.x > 0) {
        for (std::uint32_t y = 0; y < region.height; ++y) {
            sum += get_reference_luma(input,
                                      reconstructed,
                                      static_cast<int>(region.x) - 1,
                                      static_cast<int>(region.y + y));
            ++count;
        }
    }

    if (count == 0) {
        for (std::uint32_t y = 0; y < region.height; ++y) {
            for (std::uint32_t x = 0; x < region.width; ++x) {
                sum += input.get_luma(region.x + x, region.y + y);
                ++count;
            }
        }
    }

    if (count == 0) {
        return 128;
    }

    return static_cast<std::uint8_t>(sum / count);
}

std::uint8_t posi::predict_angular(const frame& input,
                                   const frame& reconstructed,
                                   const block& region,
                                   std::uint32_t local_x,
                                   std::uint32_t local_y,
                                   std::uint32_t mode_index) const
{
    const int mode = static_cast<int>(mode_index);
    const int center_mode = 18;
    const int delta = mode - center_mode;

    const int x = static_cast<int>(region.x + local_x);
    const int y = static_cast<int>(region.y + local_y);

    if (mode < center_mode) {
        const int projected_y =
            y + (delta * static_cast<int>(local_x + 1)) / 8;

        return get_reference_luma(input,
                                  reconstructed,
                                  static_cast<int>(region.x) - 1,
                                  projected_y);
    }

    if (mode > center_mode) {
        const int projected_x =
            x + (delta * static_cast<int>(local_y + 1)) / 8;

        return get_reference_luma(input,
                                  reconstructed,
                                  projected_x,
                                  static_cast<int>(region.y) - 1);
    }

    const int left =
        get_reference_luma(input, reconstructed, static_cast<int>(region.x) - 1, y);

    const int top =
        get_reference_luma(input, reconstructed, x, static_cast<int>(region.y) - 1);

    return static_cast<std::uint8_t>((left + top) / 2);
}

std::vector<std::int16_t> posi::compute_residual(
    const frame& input,
    const block& region,
    const std::vector<std::uint8_t>& predicted) const
{
    std::vector<std::int16_t> residual;
    residual.reserve(region.area());

    std::size_t index = 0;

    for (std::uint32_t y = 0; y < region.height; ++y) {
        for (std::uint32_t x = 0; x < region.width; ++x) {
            const std::uint8_t original =
                input.get_luma(region.x + x, region.y + y);

            const std::uint8_t pred =
                index < predicted.size() ? predicted[index] : 128;

            residual.push_back(
                static_cast<std::int16_t>(
                    static_cast<int>(original) - static_cast<int>(pred)
                )
            );

            ++index;
        }
    }

    return residual;
}

std::uint32_t posi::compute_satd_like_cost(
    const std::vector<std::int16_t>& residual,
    const block& region) const
{
    // TLM SATD-like approximation:
    // sum abs residual + simple local variation penalty.
    std::uint64_t sum_abs = 0;

    for (std::int16_t value : residual) {
        sum_abs += static_cast<std::uint32_t>(abs_int(value));
    }

    std::uint64_t variation = 0;

    if (region.width >= 2 && region.height >= 2 &&
        residual.size() >= static_cast<std::size_t>(region.area())) {
        for (std::uint32_t y = 0; y + 1 < region.height; ++y) {
            for (std::uint32_t x = 0; x + 1 < region.width; ++x) {
                const std::size_t idx =
                    static_cast<std::size_t>(y) * region.width + x;

                const int a = residual[idx];
                const int b = residual[idx + 1];
                const int c = residual[idx + region.width];

                variation += static_cast<std::uint32_t>(abs_int(a - b));
                variation += static_cast<std::uint32_t>(abs_int(a - c));
            }
        }
    }

    return clamp_cost_u32(sum_abs + variation / 4u);
}

std::uint32_t posi::estimate_rate(std::uint32_t mode_index,
                                  partition_mode partition,
                                  const block& region) const
{
    std::uint32_t rate = 1;

    if (mode_index == INTRA_PLANAR_MODE ||
        mode_index == INTRA_DC_MODE) {
        rate += 1;
    } else {
        rate += 3;
    }

    if (partition == partition_mode::part_split) {
        rate += 4;
    }

    if (region.width <= 8 || region.height <= 8) {
        rate += 2;
    } else if (region.width <= 16 || region.height <= 16) {
        rate += 1;
    }

    return rate;
}

partition_mode posi::decide_partition(const block& region,
                                       std::uint32_t cost) const
{
    if (region.width <= 8 || region.height <= 8) {
        return partition_mode::part_2nx2n;
    }

    const std::uint32_t area = region.area();
    if (area == 0) {
        return partition_mode::part_2nx2n;
    }

    const std::uint32_t avg_cost = cost / area;

    if (avg_cost > 32 && region.width >= 16 && region.height >= 16) {
        return partition_mode::part_split;
    }

    return partition_mode::part_2nx2n;
}

std::uint8_t posi::get_reference_luma(const frame& input,
                                      const frame& reconstructed,
                                      int x,
                                      int y) const
{
    if (!reconstructed.empty() &&
        x >= 0 &&
        y >= 0 &&
        reconstructed.in_luma_bounds(static_cast<std::uint32_t>(x),
                                     static_cast<std::uint32_t>(y))) {
        return reconstructed.get_luma(static_cast<std::uint32_t>(x),
                                      static_cast<std::uint32_t>(y));
    }

    if (!input.empty()) {
        const int max_x = static_cast<int>(input.width) - 1;
        const int max_y = static_cast<int>(input.height) - 1;

        const int cx = std::clamp(x, 0, max_x);
        const int cy = std::clamp(y, 0, max_y);

        return input.get_luma(static_cast<std::uint32_t>(cx),
                              static_cast<std::uint32_t>(cy));
    }

    return 128;
}

intra_prediction_mode posi::map_intra_mode(std::uint32_t mode_index) const
{
    if (mode_index == INTRA_PLANAR_MODE) {
        return intra_prediction_mode::planar;
    }

    if (mode_index == INTRA_DC_MODE) {
        return intra_prediction_mode::dc;
    }

    if (mode_index <= 6u) {
        return intra_prediction_mode::angular_2;
    }

    if (mode_index <= 14u) {
        return intra_prediction_mode::angular_10;
    }

    if (mode_index <= 22u) {
        return intra_prediction_mode::angular_18;
    }

    if (mode_index <= 30u) {
        return intra_prediction_mode::angular_26;
    }

    return intra_prediction_mode::angular_34;
}

} // namespace cdc::components
