// SPDX-License-Identifier: Apache-2.0
// Bit-exact comparison of the C++ pipeline with the independent Python
// reference, on the committed vectors of tests/data/vectors (generated by
// tools/gen_vectors.py). Usage: fx1_isp_test_pipeline_vectors <vectors dir>

#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <sstream>
#include <string>
#include <vector>

#include "control/control_unit.h"
#include "fx1_check.h"
#include "pipeline/isp_pipeline.h"
#include "registers/csr_desc.h"
#include "vector_io.h"

using namespace cdc::components::fx1_isp;
namespace fs = std::filesystem;

namespace {

std::vector<std::uint8_t> read_file(const fs::path &p) {
   std::ifstream f(p, std::ios::binary);
   return {std::istreambuf_iterator<char>(f), {}};
}

const csr::reg_desc *find_register(const std::string &name) {
   for (std::size_t i = 0; i < csr::num_registers; ++i) {
      if (name == csr::registers[i].name) {
         return &csr::registers[i];
      }
   }
   FX1_CHECK_EQ_CTX(1, 0, "unknown register " + name);
   return nullptr;
}

bool write_named(control_unit &cu, const std::string &name, std::uint32_t value, std::uint64_t cycle) {
   const csr::reg_desc *d = find_register(name);
   if (d) {
      cu.csr_write(d->offset, value, 0xFFFFFFFFu, cycle);
   }
   return d != nullptr;
}

bool apply_profile(control_unit &cu, const fs::path &p) {
   std::uint64_t cycle = 1;
   for (const fx1_test::csr_line &l : fx1_test::read_profile(p)) {
      if (!write_named(cu, l.reg, l.value, cycle++)) {
         return false;
      }
   }
   return true;
}

void run_vector(const fs::path &dir) {
   const std::string name = dir.filename().string();
   std::ifstream meta(dir / "meta.txt");
   std::uint32_t in_w = 0, in_h = 0, out_w = 0, out_h = 0, frames = 1;
   meta >> in_w >> in_h >> out_w >> out_h >> frames;
   const std::vector<std::uint8_t> input = read_file(dir / "input.bin");
   const std::vector<std::uint8_t> want_y = read_file(dir / "expected_y.bin");
   const std::vector<std::uint8_t> want_uv = read_file(dir / "expected_uv.bin");
   FX1_CHECK_EQ_CTX(input.size(), 2ull * in_w * in_h, name + " input size");

   control_unit cu;
   if (!apply_profile(cu, dir / "profile.csrw")) {
      return;
   }
   std::vector<std::uint8_t> got_y, got_uv;
   std::vector<std::uint16_t> line(in_w);
   pipe::isp_pipeline p;
   std::vector<std::string> warnings;
   const std::vector<fx1_test::csr_line> between = fx1_test::read_frame_writes(dir / "frames.csrw");
   for (std::uint32_t f = 0; f < frames; ++f) {  // the same input each frame; compare the last one
      std::uint64_t cycle = (std::uint64_t{f} << 20) + 1000;
      for (const fx1_test::csr_line &w : between) {  // software between frames
         if (w.frame == f) {
            write_named(cu, w.reg, w.value, cycle++);
         }
      }
      cu.accepted_sof(std::uint64_t{f + 1} << 20);  // engine order: pending commits and selections first
      const pipe::pipeline_config cfg = pipe::snapshot_config(cu);
      got_y.clear();
      got_uv.clear();
      const pipe::frame_geometry g = p.begin(
          cfg, in_w, in_h, [&](std::vector<std::uint8_t> &&r) { got_y.insert(got_y.end(), r.begin(), r.end()); },
          [&](std::vector<std::uint8_t> &&r) { got_uv.insert(got_uv.end(), r.begin(), r.end()); },
          [&](const std::string &w) { warnings.push_back(w); });
      FX1_CHECK_EQ_CTX(g.width, out_w, name + " out_w");
      FX1_CHECK_EQ_CTX(g.height, out_h, name + " out_h");
      FX1_CHECK_EQ_CTX(cu.resizer_output_geometry().width, out_w, name + " RESIZER_OUT_W");
      for (std::uint32_t y = 0; y < in_h; ++y) {
         for (std::uint32_t x = 0; x < in_w; ++x) {
            const std::size_t i = 2u * (std::size_t{y} * in_w + x);
            line[x] = static_cast<std::uint16_t>(input[i] | (input[i + 1] << 8));
         }
         p.push(line.data());
      }
      p.finish();
      pipe::end_of_frame(cu, cfg, p.stats());
   }
   // Only DEC-28 warns, once per frame; every block of the vectors is
   // implemented, so nothing else may be reported (review M3-R4).
   const bool dyn = name.find("bpc_dynamic_requested") != std::string::npos;
   FX1_CHECK_EQ_CTX(warnings.size(), dyn ? frames : 0u, name + " warnings");
   for (const std::string &w : warnings) {
      FX1_CHECK_EQ_CTX(w.find("DEC-28") != std::string::npos ? 1 : 0, 1, name + " unexpected warning: " + w);
   }
   auto compare = [&](const std::vector<std::uint8_t> &got, const std::vector<std::uint8_t> &want, const char *plane,
                      std::uint32_t width) {
      FX1_CHECK_EQ_CTX(got.size(), want.size(), name + " " + plane + " size");
      std::size_t bad = 0, first = 0;
      for (std::size_t i = 0; i < std::min(got.size(), want.size()); ++i) {
         if (got[i] != want[i] && bad++ == 0) {
            first = i;
         }
      }
      std::string where;
      if (bad) {
         where = " first at (" + std::to_string(first % width) + "," + std::to_string(first / width) + ") got " +
                 std::to_string(got[first]) + " want " + std::to_string(want[first]);
      }
      FX1_CHECK_EQ_CTX(bad, 0, name + " " + plane + " mismatches" + where);
   };
   compare(got_y, want_y, "Y", out_w);
   compare(got_uv, want_uv, "UV", out_w);

   // Published block counters and statistics, as software reads them
   // (SET lines program the readout selectors).
   std::uint64_t cycle = (std::uint64_t{frames + 1} << 20) + 1000;
   std::string sel;
   for (const fx1_test::csr_line &l : fx1_test::read_expected(dir / "expected_stats.txt")) {
      if (l.set) {
         write_named(cu, l.reg, l.value, cycle++);
         sel = " @" + l.reg + "=" + std::to_string(l.value);
      } else if (const csr::reg_desc *d = find_register(l.reg)) {
         FX1_CHECK_EQ_CTX(cu.csr_read(d->offset), l.value, name + " " + l.reg + sel);
      }
   }
}

void check_resizer_plans(const fs::path &table) {
   std::ifstream f(table);
   std::string line;
   std::size_t rows = 0;
   while (std::getline(f, line)) {
      if (line.empty() || line[0] == '#') {
         continue;
      }
      std::istringstream is(line);
      std::uint32_t w, h, scale, pass, k, ow, oh;
      is >> w >> h >> scale >> pass >> k >> ow >> oh;
      const pipe::resizer_plan p = pipe::plan_resizer(true, scale, w, h);
      const std::string ctx = line;
      FX1_CHECK_EQ_CTX(p.pass ? 1u : 0u, pass, ctx);
      FX1_CHECK_EQ_CTX(p.out_w, ow, ctx);
      FX1_CHECK_EQ_CTX(p.out_h, oh, ctx);
      if (!p.pass) {
         FX1_CHECK_EQ_CTX(p.stages, k, ctx);
         // DEC-23 invariant: the bilinear never upscales.
         FX1_CHECK_EQ_CTX(p.dec_w >= p.out_w && p.dec_h >= p.out_h ? 1 : 0, 1, ctx);
      }
      ++rows;
   }
   FX1_CHECK(rows == 160);
}

}  // namespace

int main(int argc, char **argv) {
   if (argc < 2) {
      std::cerr << "usage: " << argv[0] << " <vectors dir>\n";
      return 2;
   }
   const fs::path root = argv[1];
   std::size_t n = 0;
   for (const auto &e : fs::directory_iterator(root)) {
      if (e.is_directory()) {
         run_vector(e.path());
         ++n;
      }
   }
   FX1_CHECK(n >= 32);
   check_resizer_plans(root / "resizer_plans.txt");
   return fx1_test::summary("fx1_isp_test_pipeline_vectors");
}
