#!/usr/bin/env python3
"""Generate the forwarding headers of core_rtl/ (run from the repository root).

core_rtl/ is a model root for system integration wrappers: a wrapper adds <root>, <root>/driver and
<root>/instrumentation to its include path and includes npu_top.h. core_rtl/npu_top.h (hand-written) is the drop-in
top level; every other header that the model includes by a repository-root path (for example "sauria_types.h" from
has/has_npu_top.h, "sram/sram_top.h", "driver/libsauria_cfg.h") gets a one-line forwarding header at the same
relative path under core_rtl/, so it resolves without adding the repository root to the wrapper's include path.

usage: python3 tools/has/make_core_rtl.py [--check]
  --check  only report missing or stale forwarding headers (exit 1 if any)
"""
import os
import re
import sys

ROOT = os.path.abspath(".")
OUT = os.path.join(ROOT, "core_rtl")
SKIP_DIRS = {".backups", "backup", "fe_work", "core_rtl", "docs", "__pycache__", "npu_demo_clean", "stimuli",
             "tb_data_utilization"}
# Files a typical wrapper build requires at the model root (checked by its build script).
REQUIRED = ["npu_profile.h", "sauria_targets.h", "config_regs.h", "control/instruction_decoder.h",
            "control/sauria_dma.h", "driver/libsauria_cfg.h", "driver/sauria_run.h",
            "instrumentation/perf_counters.h"]
INC = re.compile(r'^\s*#\s*include\s+"([^"]+)"', re.M)
HEADER = "// Forwarding header of the core_rtl model root, generated by tools/has/make_core_rtl.py\n"


def targets():
    found = set(REQUIRED)
    for d, dirs, files in os.walk(ROOT):
        dirs[:] = [x for x in dirs if x not in SKIP_DIRS]
        for f in files:
            if not f.endswith((".h", ".hpp")):
                continue
            with open(os.path.join(d, f), encoding="utf-8", errors="replace") as fh:
                for t in INC.findall(fh.read()):
                    if t.startswith(".") or t == "npu_top.h":
                        continue
                    if os.path.isfile(os.path.join(ROOT, t)):
                        found.add(t)
    return sorted(found)


def content(t):
    depth = t.count("/") + 1
    return HEADER + '#include "%s%s"\n' % ("../" * depth, t)


def main():
    check = "--check" in sys.argv
    if not os.path.isfile(os.path.join(OUT, "npu_top.h")):
        sys.exit("core_rtl/npu_top.h is missing")
    bad = 0
    ts = targets()
    for t in ts:
        p = os.path.join(OUT, t)
        want = content(t)
        have = open(p, encoding="utf-8").read() if os.path.isfile(p) else None
        if have == want:
            continue
        bad += 1
        if check:
            print("stale" if have is not None else "missing", t)
        else:
            os.makedirs(os.path.dirname(p), exist_ok=True)
            with open(p, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(want)
    # Forwarding headers whose target no longer exists.
    for d, _, files in os.walk(OUT):
        for f in files:
            rel = os.path.relpath(os.path.join(d, f), OUT).replace(os.sep, "/")
            if rel not in ("npu_top.h", "README.md") and rel not in ts:
                bad += 1
                if check:
                    print("obsolete", rel)
                else:
                    os.remove(os.path.join(d, f))
                    print("removed obsolete", rel)
    print("%d forwarding headers, %d %s" % (len(ts), bad, "to update" if check else "written"))
    if check and bad:
        sys.exit(1)


if __name__ == "__main__":
    main()
