#pragma once
//
// 1:1 port of RTL sauria_core/psm/psm_wdata_manager.sv.
//
// This configuration has SRAMC_N = MEMC_W/OC_W = Y_DIM (hw_versions.py:458, `HOPTS["MEMC_W"] = HOPTS["Y"] *
// HOPTS["OC_W"]`, consistent with the OUT.CXLIM = 64 / CXSTEP = 32 register values of demo_gemm_32x32). This
// means real RTL's "narrow word packing" is DEGENERATE for this project --
// one SRAM-C word already holds a full Y-wide vector, so this class's
// wofs/elm_cnt machinery should reduce to a near-trivial passthrough here.
// Ported faithfully (not hand-simplified) so the real formulas -- not an
// assumption about what they reduce to -- decide the actual behavior.
//
#include <cstdint>

namespace sauria_rtl
{
using namespace sauria; // A1 port: shared vector/mask types stay in ::sauria, class bodies move to ::sauria_rtl.

    // Y_DIM: number of buffered elements (RTL's Y). SRAMC_N: number of
    // output word-slots (RTL's SRAMC_N = SRAMC_W/OC_W). VecT: Y_DIM-wide
    // input vector type (psum_vector_t<Y_DIM,T_PSUM>). ElemT: per-slot
    // output element type (T_PSUM).
    template <int Y_DIM, int SRAMC_N, typename VecT, typename ElemT>
    class PsmWdataManager
    {
    public:
        struct Inputs
        {
            VecT fifo_dout;       // i_fifo_dout (Y_DIM-wide buffered vector)
            bool feeder_en = false;  // i_feeder_en
            bool clearbuff = false;  // i_clearbuff
            uint64_t mask = 0;       // i_mask, bit j = word-slot j active
            bool fifo_pop = false;   // i_fifo_pop
        };

        struct Outputs
        {
            uint64_t sramc_wmask = 0;      // o_sramc_wmask
            bool fifo_pop = false;         // o_fifo_pop
            ElemT sramc_wdata[SRAMC_N]{};  // o_sramc_wdata, per word-slot
        };

        void reset()
        {
            mask_q1_ = 0;
            mask_q2_ = 0;
            fifo_pop_q_ = false;
            elm_cnt_q_ = 0;
            for (int j = 0; j < SRAMC_N; j++)
                outbuf_q_[j] = ElemT{};
        }

        // RTL: `assign o_fifo_pop = fifo_pop_q;` -- a plain wire read of a
        // register, needed by psm_top.sv's `buff_shift_en` combinational
        // logic BEFORE this cycle's tick() (which needs buff_shift_en's
        // result as an INPUT) can run. Safe to read pre-tick state here
        // since fifo_pop_q only changes via THIS class's own commit.
        bool peek_fifo_pop() const { return fifo_pop_q_; }
        // temp debug accessors, same pattern as-177
        // (removed after use there) -- reused here to trace elm_cnt_q_/
        // mask_q1_ alignment against idxcnt's sram_addr/mask.
        uint32_t peek_elm_cnt() const { return elm_cnt_q_; }
        uint64_t peek_mask_q1() const { return mask_q1_; }

        Outputs tick(const Inputs &in)
        {
            // ---------- Phase 1: combinational (pre-tick register state) ----------

            // Word Offset => location of the first 0->1 transition in
            // mask_q1_ (RTL lines 134-140: default 0, only updated by the
            // rising-edge search over j=1..SRAMC_N-1).
            int wofs = 0;
            for (int j = 1; j < SRAMC_N; j++)
            {
                bool bit_j = (mask_q1_ >> j) & 1ULL;
                bool bit_jm1 = (mask_q1_ >> (j - 1)) & 1ULL;
                if (bit_j && !bit_jm1)
                    wofs = j;
            }

            // Assignment to buffers based on element index counter & mask
            // (RTL lines 142-149).
            bool outbuf_en[SRAMC_N];
            ElemT outbuf_d[SRAMC_N];
            for (int j = 0; j < SRAMC_N; j++)
            {
                bool bit_j = (mask_q1_ >> j) & 1ULL;
                outbuf_en[j] = bit_j;
                if (bit_j)
                {
                    int idx = (int)elm_cnt_q_ + (j - wofs);
                    // Real RTL indexes buff_elements[elm_cnt_q+(j-wofs)]
                    // unconditionally when mask_q1[j] is set; masks
                    // generated by psm_idxcnt.sv are always a contiguous
                    // active range starting at wofs, so idx should stay in
                    // [0,Y_DIM) whenever bit_j is set. Guarded defensively
                    // (rather than relying on that invariant) to avoid
                    // undefined behavior if it's ever violated.
                    outbuf_d[j] = (idx >= 0 && idx < Y_DIM) ? in.fifo_dout[idx] : ElemT{};
                }
                else
                {
                    outbuf_d[j] = ElemT{};
                }
            }

            // Element Index Counter step = popcount(mask_q1_) (RTL lines
            // 177-194).
            uint32_t elm_cnt_step = 0;
            for (int b = 0; b < SRAMC_N; b++)
                elm_cnt_step += (uint32_t)((mask_q1_ >> b) & 1ULL);
            const uint32_t elm_cnt_d =
                (fifo_pop_q_ || in.clearbuff) ? 0u : (elm_cnt_q_ + elm_cnt_step);

            // ---------- Outputs (RTL lines 211-212, 97-103: read the
            // PRE-tick _q registers directly). ----------
            Outputs out;
            out.sramc_wmask = mask_q2_;
            out.fifo_pop = fifo_pop_q_;
            for (int j = 0; j < SRAMC_N; j++)
                out.sramc_wdata[j] = outbuf_q_[j];

            // ---------- Phase 2: commit ----------
            // wmask_reg (RTL lines 110-122): mask_q1<=i_mask; mask_q2<=
            // mask_q1 (the PRE-tick value, i.e. snapshot before overwrite);
            // fifo_pop_q<=i_fifo_pop. All gated by i_feeder_en only (no
            // separate clear branch in this particular always_ff).
            if (in.feeder_en)
            {
                const uint64_t pre_mask_q1 = mask_q1_;
                mask_q1_ = in.mask;
                mask_q2_ = pre_mask_q1;
                fifo_pop_q_ = in.fifo_pop;
            }

            // outbuf_reg (RTL lines 159-171): per-slot enable.
            for (int j = 0; j < SRAMC_N; j++)
            {
                if (in.feeder_en && outbuf_en[j])
                    outbuf_q_[j] = outbuf_d[j];
            }

            // el_cnt_reg (RTL lines 197-205).
            if (in.feeder_en || in.clearbuff)
                elm_cnt_q_ = elm_cnt_d;

            return out;
        }

    private:
        uint64_t mask_q1_{0};
        uint64_t mask_q2_{0};
        bool fifo_pop_q_{false};
        uint32_t elm_cnt_q_{0};
        ElemT outbuf_q_[SRAMC_N]{};
    };

} // namespace sauria_rtl
